In [1]:
import pandas as pd

In [2]:
df = pd.read_json('./new_data/dev_v2.1.json.gz')

In [3]:
header = ['query_id', 'query', 'passage_text', 'label', 'passage_id']
test_header = ['query_id', 'query', 'passage_text', 'passage_id']

In [4]:
df_formated = pd.DataFrame(columns=header)

In [5]:
df_formated

Empty DataFrame
Columns: [query_id, query, passage_text, label, passage_id]
Index: []

In [6]:
df

,answers,passages,query,query_id,query_type,wellFormedAnswers
0,[A corporation is a company or group of people...,"[{'is_selected': 0, 'passage_text': 'A company...",. what is a corporation?,1102432,DESCRIPTION,[]
1,[Rachel Carson writes The Obligation to Endure...,"[{'is_selected': 0, 'passage_text': 'Read to w...",why did rachel carson write an obligation to e...,1102431,DESCRIPTION,[]
10,[No Answer Present.],"[{'is_selected': 0, 'passage_text': 'The Progr...",why did the progressive movement fail to advan...,1102421,DESCRIPTION,[]
100,[No Answer Present.],"[{'is_selected': 0, 'passage_text': 'On an ave...",why do police need to understand what the fore...,1102315,DESCRIPTION,[]
1000,[No Answer Present.],"[{'is_selected': 0, 'passage_text': 'A: Very, ...",do owls eat in the day,1101280,NUMERIC,[]
10000,"[The symptoms of a dying mouse are runny eyes,...","[{'is_selected': 0, 'passage_text': 'This can ...",symptoms of a dying mouse,1090282,ENTITY,[]
100000,"[Globally 8,640,000 lightning strikes per day.]","[{'is_selected': 0, 'passage_text': 'Lightning...",average number of lightning strikes per day,39449,NUMERIC,[]
100001,"[Yes, over fertilizing can burn lawn.]","[{'is_selected': 0, 'passage_text': 'Verify th...",can you burn your lawn with fertilizer,76162,DESCRIPTION,[]
100002,[No Answer Present.],"[{'is_selected': 0, 'passage_text': 'Protists ...",are volvox autotrophic or heterotrophic,26117,DESCRIPTION,[]
100003,[No Answer Present.],"[{'is_selected': 0, 'passage_text': 'However, ...",average force of a raindrop,36558,NUMERIC,[]
100004,[No Answer Present.],"[{'is_selected': 0, 'passage_text': 'Low Sodiu...",chart for foods low in potassium.,90836,ENTITY,[]
100005,[No Answer Present.],"[{'is_selected': 0, 'passage_text': 'Young cro...",are saltwater crocodiles legal pets yahoo,24776,DESCRIPTION,[]
100006,[No Answer Present.],"[{'is_selected': 0, 'passage_text': 'Current t...",dayton ohio time is what,115858,NUMERIC,[]
100007,[The meaning of the name Goch is red.],"[{'is_selected': 0, 'passage_text': 'See the G...",goch meaning,195512,DESCRIPTION,[]
100008,[No Answer Present.],"[{'is_selected': 0, 'passage_text': 'b.) I see...",does drinking water help eczema,165720,DESCRIPTION,[]
100009,[No Answer Present.],"[{'is_selected': 0, 'passage_text': 'Innocent’...",how much money has innocet donated to charity,325255,NUMERIC,[]
10001,[acidic and extremely painful is symptom of a ...,"[{'is_selected': 0, 'passage_text': 'Pain from...",symptoms of a gastric ulcer in women,1090280,ENTITY,[]
100010,[For anxiety treatment is 1 mg two to three ti...,"[{'is_selected': 0, 'passage_text': 'Pdoc gave...",how often can ativan be taken,331318,NUMERIC,[]
100011,[No Answer Present.],"[{'is_selected': 0, 'passage_text': 'Oscars: '...",how many oscars did star wars a new home win?,290702,NUMERIC,[]
100012,[William Bradford served thirty years as Gover...,"[{'is_selected': 0, 'passage_text': 'Added 201...",how many years did william bradford serve as g...,300674,NUMERIC,[]
100013,"[2,662]","[{'is_selected': 0, 'passage_text': 'City of A...",albany mn population,15177,NUMERIC,"[The population of Albany, Minnesota is 2,662. ]"
100014,[No Answer Present.],"[{'is_selected': 0, 'passage_text': 'Trump tig...",how many inspector general nominations from trump,286599,NUMERIC,[]
100015,"[It means preventing, hindering, or acting as ...","[{'is_selected': 1, 'passage_text': 'Adjective...",define preventive,125705,DESCRIPTION,[]
100016,[No Answer Present.],"[{'is_selected': 0, 'passage_text': 'Panda Exp...",does mcdonald's own panda express,168814,DESCRIPTION,[]
100017,"[An infection, heredity or an abnormality of t...","[{'is_selected': 0, 'passage_text': 'Achalasia...",causes of achalasia,85224,DESCRIPTION,[]
100018,[No Answer Present.],"[{'is_selected': 0, 'passage_text': 'Fields in...",how many direct subclasses can a superclass have,282470,NUMERIC,[]
100019,[The Volcano forecast for Apr 12 is 52 degrees...,"[{'is_selected': 1, 'passage_text': 'Volcano 1...","current weather in volcano, ca",114414,DESCRIPTION,[The Volcano forecast for Apr 12 is 52 degrees...
10002,[No Answer Present.],"[{'is_selected': 0, 'passage_text': 'Cervical ...",symptoms of a lumbar disc ready to rupture,1090279,ENTITY,[]
100020,[No Answer Present.],"[{'is_selected': 0, 'passage_text': '© 2017 Ac...",december weather in grand cayman,116220,DESCRIPTION,[]
100021,[No Answer Present.],"[{'is_selected': 0, 'passage_text': 'Average U...",average salary in uzbekistan,42885,NUMERIC,[]
...,...,...,...,...,...,...
99972,[No Answer Present.],"[{'is_selected': 0, 'passage_text': 'How to in...",how to run mac on windows,378051,DESCRIPTION,[]
99973,[No Answer Present.],"[{'is_selected': 0, 'passage_text': 'The Role ...",how does iron affect blood,226608,DESCRIPTION,[]
99974,[No Answer Present.],"[{'is_selected': 0, 'passage_text': 'In low-in...",how has southbank changed economically over th...,235064,DESCRIPTION,[]
99975,[About 12 minutes.],"[{'is_selected': 0, 'passage_text': '{{model.a...",how long do you cook a hard boiled egg,247441,NUMERIC,[]
99976,[No Answer Present.],"[{'is_selected': 0, 'passage_text': 'After the...",how to educate about pregnancy discrimination ...,356983,DESCRIPTION,[]
99977,[It is recommended that you take a practice no...,"[{'is_selected': 1, 'passage_text': 'Oklahoma ...",how to become a notary oklahoma,345237,DESCRIPTION,[It is recommended that you take a practice no...
99978,[No Answer Present.],"[{'is_selected': 0, 'passage_text': 'Level 1 (...",how to delete birthday from contacts in iphone...,354385,DESCRIPTION,[]
99979,[No Answer Present.],"[{'is_selected': 0, 'passage_text': 'To remove...",how do camelbaks work,216604,DESCRIPTION,[]
9998,[The symptoms of gallbladder attack include ri...,"[{'is_selected': 0, 'passage_text': 'CT scan m...",symptoms gallbladder attack,1090284,ENTITY,[]
99980,[No Answer Present.],"[{'is_selected': 0, 'passage_text': 'It can do...",how many watts in a marineland led light,299618,NUMERIC,[]
99981,[No Answer Present.],"[{'is_selected': 0, 'passage_text': 'Sertich b...",colorado dinosaur fossils found,94824,ENTITY,[]
99982,[25-26 minutes.],"[{'is_selected': 0, 'passage_text': '1 Top wit...",how long do you bake muffins,247194,NUMERIC,[]
99983,[No Answer Present.],"[{'is_selected': 0, 'passage_text': 'Step 2: O...",how to create format in javascript,353570,DESCRIPTION,[]
99984,[No Answer Present.],"[{'is_selected': 0, 'passage_text': 'Zone 6: P...",easy care shrubs for garden beds,177519,ENTITY,[]
99985,[$2 to $5 per square foot.],"[{'is_selected': 0, 'passage_text': 'Vinyl, ac...",cost per foot on hardy plank installation,108172,NUMERIC,[]
99986,[$ 50 to $ 200],"[{'is_selected': 1, 'passage_text': 'according...",how much does a pap smear cost,310713,NUMERIC,[]
99987,[1 to 2 days.],"[{'is_selected': 0, 'passage_text': 'When I wa...",how long does it take to mail a card usps,257688,NUMERIC,[]
99988,[The meaning of glioma is a tumor springing fr...,"[{'is_selected': 0, 'passage_text': 'Optic Gli...",glioma meaning,195199,DESCRIPTION,[]
99989,[No Answer Present.],"[{'is_selected': 0, 'passage_text': 'Leave law...",do employers have to comply with state and fed...,156154,DESCRIPTION,[]
9999,[The symptoms of a bad rear main seal are slip...,"[{'is_selected': 0, 'passage_text': 'If you di...",symptoms of a bad main seal,1090283,ENTITY,[]
99990,"[Pizza, pasta and ice cream.]","[{'is_selected': 0, 'passage_text': 'Kashmiri ...",different types of cuisines,150337,DESCRIPTION,[]
99991,[No Answer Present.],"[{'is_selected': 0, 'passage_text': 'Apartheid...",describe how apartheid benefited white colonizers,141588,DESCRIPTION,[]
99992,"[Yes, electric cleansers are safe.]","[{'is_selected': 0, 'passage_text': 'Features ...",are electric cleansers safe?,22241,DESCRIPTION,[]
99993,[No Answer Present.],"[{'is_selected': 0, 'passage_text': 'Typical H...",how much to renovate a small ensuite,329433,NUMERIC,[]
99994,[No Answer Present.],"[{'is_selected': 0, 'passage_text': 'It is one...",average temperature in portland,45356,NUMERIC,[]
99995,"[It is defined as the quality of being wide, o...","[{'is_selected': 0, 'passage_text': '1 The sta...",define width,129177,NUMERIC,[]
99996,[Human Resource Management is the term used to...,"[{'is_selected': 1, 'passage_text': 'Human Res...",forbes definition of human resource management,190655,DESCRIPTION,[]
99997,[No Answer Present.],"[{'is_selected': 0, 'passage_text': 'Cleans up...",how long to wax urethane paint,272679,NUMERIC,[]
99998,[No Answer Present.],"[{'is_selected': 0, 'passage_text': '1 Set up ...",easiest way to check accounts payable entered ...,177416,DESCRIPTION,[]
99999,[List the elements you want to include in a he...,"[{'is_selected': 0, 'passage_text': 'Business ...",how to offer health insurance to employees,371455,DESCRIPTION,[]

In [4]:
df.loc[0]['passages']

[{'is_selected': 0,
  'passage_text': 'A company is incorporated in a specific nation, often within the bounds of a smaller subset of that nation, such as a state or province. The corporation is then governed by the laws of incorporation in that state. A corporation may issue stock, either private or public, or may be classified as a non-stock corporation. If stock is issued, the corporation will usually be governed by its shareholders, either directly or indirectly.',
  'url': 'http://www.wisegeek.com/what-is-a-corporation.htm'},
 {'is_selected': 0,
  'passage_text': 'Today, there is a growing community of more than 2,100 Certified B Corps from 50 countries and over 130 industries working together toward 1 unifying goal: to redefine success in business. Join the Movement',
  'url': 'https://www.bcorporation.net/what-are-b-corps'},
 {'is_selected': 0,
  'passage_text': 'Corporation definition, an association of individuals, created by law or under authority of law, having a continuous existence independent of the existences of its members, and powers and liabilities distinct from those of its members. See more.',
  'url': 'http://www.dictionary.com/browse/corporation'},
 {'is_selected': 0,
  'passage_text': 'Examples of corporation in a Sentence. 1  He works as a consultant for several large corporations. 2  a substantial corporation that showed that he was a sucker for all-you-can-eat buffets.',
  'url': 'https://www.merriam-webster.com/dictionary/corporation'},
 {'is_selected': 0,
  'passage_text': '1: a government-owned corporation (as a utility or railroad) engaged in a profit-making enterprise that may require the exercise of powers unique to government (as eminent domain) — called also government corporation, publicly held corporation',
  'url': 'https://www.merriam-webster.com/dictionary/corporation'},
 {'is_selected': 1,
  'passage_text': "McDonald's Corporation is one of the most recognizable corporations in the world. A corporation is a company or group of people authorized to act as a single entity (legally a person) and recognized as such in law. Early incorporated entities were established by charter (i.e. by an ad hoc act granted by a monarch or passed by a parliament or legislature).",
  'url': 'https://en.wikipedia.org/wiki/Corporation'},
 {'is_selected': 0,
  'passage_text': "Corporations are owned by their stockholders (shareholders) who share in profits and losses generated through the firm's operations, and have three distinct characteristics (1) Legal existence: a firm can (like a person) buy, sell, own, enter into a contract, and sue other persons and firms, and be sued by them.",
  'url': 'http://www.businessdictionary.com/definition/corporation.html'},
 {'is_selected': 0,
  'passage_text': 'An Association is an organized group of people who share in a common interest, activity, or purpose. 1  Start a business Plan your business. Create your business structure Types of business structures. 2  Change or update your business Add a new location to your existing business. Add an endorsement to your existing business.',
  'url': 'http://bls.dor.wa.gov/ownershipstructures.aspx'},
 {'is_selected': 0,
  'passage_text': 'B Corp certification shines a light on the companies leading the global movement...',
  'url': 'https://www.bcorporation.net/'},
 {'is_selected': 0,
  'passage_text': 'LLCs offer greater flexibility when it comes to income taxes. 1  The owner or member of an LLC can have their income taxed in three ways: 2  A single owner LLC is treated as a Schedule C (sole proprietor) for tax purposes.',
  'url': 'http://www.investorwords.com/article/s-corporation-vs-llc.html'}]

In [7]:
df_train = pd.read_json('./new_data/train_v2.1.json.gz')

In [8]:
df_test = pd.read_json('./new_data/eval_v2.1_public.json.gz')

In [9]:
df_train.head()

,answers,passages,query,query_id,query_type,wellFormedAnswers
0,[The immediate impact of the success of the ma...,"[{'is_selected': 1, 'passage_text': 'The prese...",)what was the immediate impact of the success ...,1185869,DESCRIPTION,[]
1,[Restorative justice that fosters dialogue bet...,"[{'is_selected': 0, 'passage_text': 'group dis...",_________ justice is designed to repair the ha...,1185868,DESCRIPTION,[]
10,[The reasons why Stalin wanted to control East...,"[{'is_selected': 0, 'passage_text': 'Western b...",why did stalin want control of eastern europe,1185854,DESCRIPTION,[]
100,[Nails rust in water because water allows the ...,"[{'is_selected': 0, 'passage_text': 'what to D...",why do nails get rusty,1185755,DESCRIPTION,[]
1000,"[Depona Ab is a library in Vilhelmina, Sweden.]","[{'is_selected': 0, 'passage_text': 'A preview...",depona ab,1184773,DESCRIPTION,[]

In [20]:
df_test

,passages,query,query_id,query_type
0,[{'passage_text': 'Color hex is a easy to use ...,#ffffff color code,1136966,ENTITY
1,[{'passage_text': 'Why Visa Stock Is Dropping ...,why did qbe stock drop?,1136965,DESCRIPTION
10,[{'passage_text': 'Although the European power...,why did the monroe doctrine originate?,1136956,DESCRIPTION
100,[{'passage_text': 'Global wind patterns. Globa...,why do trade winds move in this pattern,1136841,DESCRIPTION
1000,[{'passage_text': 'Erie Canal Distance Tables ...,distance between erie in buffalo new york,1135787,NUMERIC
10000,"[{'passage_text': 'If you have cancer, your do...",symptoms of hypercalcemia of malignancy,1125025,ENTITY
100000,[{'passage_text': 'The asteroid belt is nothin...,how many days would it take to get to pluto,281922,NUMERIC
100001,[{'passage_text': 'Low Blood Pressure. When yo...,causes of dizziness when you stand up,86062,DESCRIPTION
100002,[{'passage_text': 'Pennsylvania State Tax Info...,does kansas charge hotel tax for government em...,167929,DESCRIPTION
100003,[{'passage_text': 'J & J Hay Farms sells only ...,can you use horse trailer for hay,80665,DESCRIPTION
100004,[{'passage_text': 'Dew Point Temperature (Td)....,define dew point.,120233,DESCRIPTION
100005,[{'passage_text': '1 The IBD 200 list publishe...,cost of ibd digital,104691,NUMERIC
100006,[{'passage_text': 'Chai Tea Latte Calories. A ...,how many calories in a grande iced chai tea wi...,276902,NUMERIC
100007,"[{'passage_text': 'The Doctor's Diet Cookbook,...",has dr travis stork ever divorced,198914,DESCRIPTION
100008,[{'passage_text': 'Get your EMT-B certificatio...,emt schooling how long,180241,NUMERIC
100009,[{'passage_text': 'Raising Turkeys as a 4-H or...,how to raise turkeys for ffa,374636,DESCRIPTION
10001,[{'passage_text': 'a soup or stew containing s...,bouillabaisse pronunciation,1125024,DESCRIPTION
100010,"[{'passage_text': 'In very simple terms, it's ...",how fast is a jet going as it lifts off?,234133,NUMERIC
100011,[{'passage_text': 'Utility companies. Arrange ...,how soon should you notify people that you're ...,339930,NUMERIC
100012,[{'passage_text': 'Lily Rader Quick Bio Info. ...,how old is lily rader,335726,NUMERIC
100013,[{'passage_text': 'Naples Home Prices. Since 2...,average time period to sell a home naples fl,46155,NUMERIC
100014,[{'passage_text': 'When You Can Discharge a Ta...,can you claim bankruptcy on taxes,76402,DESCRIPTION
100015,[{'passage_text': 'You can tell a person pract...,how can i know if someone is doing witchcraft ...,210530,DESCRIPTION
100016,[{'passage_text': 'Melania Trump’s journey to ...,how old is melania trump,335954,NUMERIC
100017,"[{'passage_text': 'As you lay pavers down, mak...",how much for a paver patio,319757,NUMERIC
100018,[{'passage_text': 'What is the difference betw...,difference between natural and processed sugar,148039,DESCRIPTION
100019,[{'passage_text': 'When to remodel: You can do...,how much does a bathroom remodel,308586,NUMERIC
10002,[{'passage_text': 'Quick Answer. Kidney stone ...,symptoms of kidneys in women,1125023,ENTITY
100020,[{'passage_text': 'Without any fluids (either ...,how long can a human go safely without having ...,241269,NUMERIC
100021,[{'passage_text': 'The reproductive system is ...,are seminal vesicles affected by testicular to...,24854,DESCRIPTION
...,...,...,...,...
99972,[{'passage_text': 'Neal McDonough's height is ...,how tall is neal mcdonough,341221,NUMERIC
99973,[{'passage_text': 'Squirrels don’t eat fruit a...,does sulfa damage grass,171908,DESCRIPTION
99974,[{'passage_text': 'There are four queens in a ...,how many queens are in a deck of cards,294226,NUMERIC
99975,[{'passage_text': 'The recommended dosage is 5...,how many low dose aspirin for dog,287953,NUMERIC
99976,[{'passage_text': 'Thread: Prostate Cancer Bio...,are prostate biopsies ever negative,24494,DESCRIPTION
99977,[{'passage_text': '1 Calories Burned For Spark...,calories in half a toast,60350,NUMERIC
99978,[{'passage_text': 'Size & Shape Not just large...,how long does it take for a raven to hatch,253192,NUMERIC
99979,[{'passage_text': 'Judicial Council forms can ...,cost to file rfo in riverside court,109370,NUMERIC
9998,[{'passage_text': 'Consider the set of signs a...,symptoms of hh,1125027,ENTITY
99980,"[{'passage_text': 'Reforestation, on a larger ...",actions humans can take to help lessen the eff...,10774,DESCRIPTION
99981,[{'passage_text': 'It makes sense to spend a l...,how much do spend on a wedding shower gift,307385,NUMERIC
99982,[{'passage_text': 'Screenshot by Dennis O'Reil...,export from my contacts to shared contacts out...,184165,DESCRIPTION
99983,[{'passage_text': 'Hi Factors would be your wo...,how long are you out of work with back surgery...,240215,NUMERIC
99984,[{'passage_text': 'Gauging intensity using you...,how can you measure intensity during a workout?,211299,DESCRIPTION
99985,[{'passage_text': 'Related Items. All states p...,cortana what is the drinking age in new jersey,100026,NUMERIC
99986,[{'passage_text': 'E.g. if a variable is of ty...,how to declare variables in python,354157,DESCRIPTION
99987,[{'passage_text': 'Relieving the Swelling. See...,can facial swelling cause vertigo,67250,DESCRIPTION
99988,[{'passage_text': 'Chronic constipation may le...,foods that cause hard stools,189196,ENTITY
99989,[{'passage_text': 'Rash is a symptom that caus...,cause of perfect triangle rash on forearm,84480,DESCRIPTION
9999,[{'passage_text': 'Hydromyelia Information Pag...,symptoms of hydromyelia,1125026,ENTITY
99990,[{'passage_text': 'How to Install an Exhaust S...,can i modify my smart muffler,69285,DESCRIPTION
99991,[{'passage_text': 'Only took until the 100th s...,how many years did cubs not win,300633,NUMERIC
99992,[{'passage_text': 'The lymphatic system has th...,how often to do lymphatic drainage massage,332649,NUMERIC
99993,[{'passage_text': 'Nitrogen atoms that are par...,are aromatic diamines highly reactive,20963,DESCRIPTION
99994,[{'passage_text': 'Rabbits stop eating for man...,causes of stop eating,88486,DESCRIPTION
99995,[{'passage_text': 'Kidney stones are chunks of...,can you die from a kidney stone,76799,DESCRIPTION
99996,[{'passage_text': 'This document is Cisco Publ...,how to put supervisor module standby hot cisco,374435,DESCRIPTION
99997,[{'passage_text': 'Chauvinism is an exaggerate...,define male chauvinism,123628,DESCRIPTION
99998,[{'passage_text': 'In Irish Gaelic: 'A ghra gh...,How to say my love in irish,4331,DESCRIPTION
99999,[{'passage_text': 'Typical costs: 1 Full-time...,how much does it cost to go to college online,315646,NUMERIC

In [5]:
df_train

,answers,passages,query,query_id,query_type,wellFormedAnswers
0,[The immediate impact of the success of the ma...,"[{'is_selected': 1, 'passage_text': 'The prese...",)what was the immediate impact of the success ...,1185869,DESCRIPTION,[]
1,[Restorative justice that fosters dialogue bet...,"[{'is_selected': 0, 'passage_text': 'group dis...",_________ justice is designed to repair the ha...,1185868,DESCRIPTION,[]
10,[The reasons why Stalin wanted to control East...,"[{'is_selected': 0, 'passage_text': 'Western b...",why did stalin want control of eastern europe,1185854,DESCRIPTION,[]
100,[Nails rust in water because water allows the ...,"[{'is_selected': 0, 'passage_text': 'what to D...",why do nails get rusty,1185755,DESCRIPTION,[]
1000,"[Depona Ab is a library in Vilhelmina, Sweden.]","[{'is_selected': 0, 'passage_text': 'A preview...",depona ab,1184773,DESCRIPTION,[]
10000,[No Answer Present.],"[{'is_selected': 0, 'passage_text': 'While Chi...",is the atlanta airport the busiest in the world,1174762,LOCATION,[]
100000,"[$43,746 for the 2014-2015 academic year.]","[{'is_selected': 0, 'passage_text': 'the cost ...",nyu tuition cost,467556,NUMERIC,[]
100001,[Before the age of 2–4 years.],"[{'is_selected': 0, 'passage_text': 'In an eff...",at what age do kids start to hold memories,28213,NUMERIC,[]
100002,[Americans brush for just under the two minute...,"[{'is_selected': 0, 'passage_text': 'Your dent...",average teeth brushing time,44588,NUMERIC,[]
100003,"[Yes, funner is a word.]","[{'is_selected': 0, 'passage_text': 'Taken fro...",is funner a word?,410717,DESCRIPTION,[]
100004,[No Answer Present.],"[{'is_selected': 0, 'passage_text': 'Phloem is...",what direction does phloem flow,620830,DESCRIPTION,[]
100005,"[An abbreviation of Conformite Conformité, eur...","[{'is_selected': 0, 'passage_text': 'CE Certif...",what is ce certified,728808,DESCRIPTION,[]
100006,[No Answer Present.],"[{'is_selected': 0, 'passage_text': 'McDonald'...",artin chicken mcdonalds calories,27022,NUMERIC,[]
100007,[No Answer Present.],"[{'is_selected': 0, 'passage_text': 'Panglao i...",is panglao island safe,420332,DESCRIPTION,[]
100008,[No Answer Present.],"[{'is_selected': 0, 'passage_text': 'Synonyms ...",what is calomel powder used for?,727194,DESCRIPTION,[]
100009,[No Answer Present.],"[{'is_selected': 0, 'passage_text': 'We will u...",sum of squares of even numbers formula,505196,NUMERIC,[]
10001,[The customer support phone number of BancFirs...,"[{'is_selected': 0, 'passage_text': 'Oklahoma ...",bancfirst customer service number,1174761,NUMERIC,[]
100010,[No Answer Present.],"[{'is_selected': 0, 'passage_text': 'For the f...",what is happening in montreal in august?,753571,DESCRIPTION,[]
100011,"[DeWitt is located in Clinton County, Michigan...","[{'is_selected': 0, 'passage_text': 'DeWitt wa...",what county is dewitt michigan in?,605123,LOCATION,[]
100012,[No Answer Present.],"[{'is_selected': 0, 'passage_text': 'To create...",how to create msn email address,353608,DESCRIPTION,[]
100013,[A motorized oxygen mask doesn't qualify to mo...,"[{'is_selected': 1, 'passage_text': 'It might ...",using cpap without prescription,534802,DESCRIPTION,[]
100014,[It allows passengers to check-in to a flight ...,"[{'is_selected': 0, 'passage_text': 'A confirm...",what is early bird check in southwest,742216,ENTITY,[]
100015,[No Answer Present.],"[{'is_selected': 0, 'passage_text': 'Then you ...",excel if as an array function,182970,DESCRIPTION,[]
100016,[Bartholomew],"[{'is_selected': 0, 'passage_text': 'WELCOME T...",what county is columbus city in,604568,LOCATION,[Columbus is a city in Bartholomew County.]
100017,[Social security administration in Bellevue Wa...,"[{'is_selected': 0, 'passage_text': 'Local soc...",social security administration in bellevue wa ...,499805,NUMERIC,[]
100018,[Yes whiskers are used to help balance as well...,"[{'is_selected': 0, 'passage_text': 'Yes, whis...",are whiskers on cats used for balance,26191,DESCRIPTION,[]
100019,"[Shelton is in Fairfield County, Connecticut, ...","[{'is_selected': 0, 'passage_text': 'My husban...","what county is shelton, ct",612660,LOCATION,[]
10002,"[Yes, the bachelor is legal.]","[{'is_selected': 0, 'passage_text': 'Arconic’s...",is the bachelor legal,1174759,DESCRIPTION,[]
100020,"[Average $111,082,]","[{'is_selected': 1, 'passage_text': 'Bp Americ...",what is BP level j salary,672511,NUMERIC,[]
100021,[No Answer Present.],"[{'is_selected': 0, 'passage_text': '$8,532 - ...",how.much does squirrel.pos cost,388851,NUMERIC,[]
...,...,...,...,...,...,...
99972,[Yes],"[{'is_selected': 0, 'passage_text': 'He was th...",was william henry harrison a republican,541259,DESCRIPTION,[]
99973,"[Fairbury is in Livingston County, Illinois.]","[{'is_selected': 1, 'passage_text': '407 Walnu...",what county is fairbury il,605770,LOCATION,[]
99974,[No Answer Present.],"[{'is_selected': 0, 'passage_text': 'Without h...",how much does call of arms cost,313324,NUMERIC,[]
99975,[No Answer Present.],"[{'is_selected': 0, 'passage_text': 'You are H...",is marijuana decriminalized in new york,417294,DESCRIPTION,[]
99976,[No Answer Present.],"[{'is_selected': 0, 'passage_text': 'And the e...",what is asus computer monitor smart view,720480,DESCRIPTION,[]
99977,"[11 pounds, 22-50 pounds]","[{'is_selected': 0, 'passage_text': 'Rated 4 o...",weight evenflo maestro,547249,NUMERIC,[The weight of Evenflo Maestro is 11 pounds.]
99978,[No Answer Present.],"[{'is_selected': 0, 'passage_text': 'On Shasta...",how long did it take to fill shasta lake,243863,NUMERIC,[]
99979,[No Answer Present.],"[{'is_selected': 0, 'passage_text': 'Learn how...",random number generator excel freeze,485213,NUMERIC,[]
9998,"[Yes, iPad Pro is water resistant.]","[{'is_selected': 0, 'passage_text': 'Apple's n...",is the apple ipad water resistant?,1174764,DESCRIPTION,[]
99980,[No Answer Present.],"[{'is_selected': 0, 'passage_text': 'To schedu...",size comparison between new york and seattle w...,498842,NUMERIC,[]
99981,[908 kWh],"[{'is_selected': 1, 'passage_text': 'The avera...",average kwh per household in us,38107,NUMERIC,[]
99982,[No Answer Present.],"[{'is_selected': 0, 'passage_text': 'The guida...",what is a dependent child according to the irs,680894,DESCRIPTION,[]
99983,[No Answer Present.],"[{'is_selected': 0, 'passage_text': 'Family an...",what is division fcs,740389,DESCRIPTION,[]
99984,[No Answer Present.],"[{'is_selected': 0, 'passage_text': 'ITRACONAZ...",itraconazole cost for dogs,432460,NUMERIC,[]
99985,"[Yes, Luxury vinyl flooring is a diy job.]","[{'is_selected': 1, 'passage_text': 'Luxury vi...",is vinyl flooring a diy job,430897,DESCRIPTION,[]
99986,[A floating museum is in New York City.],"[{'is_selected': 1, 'passage_text': 'Intrepid ...",what city is a floating museum,595815,LOCATION,[]
99987,[No Answer Present.],"[{'is_selected': 0, 'passage_text': 'Language ...",how does language interaction help a language ...,226712,ENTITY,[]
99988,"[Carbon dioxide, methane and other greenhouse ...","[{'is_selected': 1, 'passage_text': 'Global wa...",what causes the greenhouse effect,592625,DESCRIPTION,[]
99989,[No Answer Present.],"[{'is_selected': 0, 'passage_text': '© Lisa Te...",how can i increase my sperm count,210510,DESCRIPTION,[]
9999,"[Yes, the asthenosphere made of iron and nickel.]","[{'is_selected': 1, 'passage_text': 'The asthe...",is the asthenosphere made of iron and nickel,1174763,DESCRIPTION,[]
99990,[No Answer Present.],"[{'is_selected': 0, 'passage_text': 'Select a ...",how to limit excel data by date,366779,DESCRIPTION,[]
99991,[Amuse means keeping yourself or someone else ...,"[{'is_selected': 0, 'passage_text': 'Much late...",the definition of amuse,515137,DESCRIPTION,[]
99992,"[WBC is 5 to 10 K/uL, HGB is 12 to 17.4 g/dL.]","[{'is_selected': 0, 'passage_text': 'A complet...",what is human blood value on a cbc,756122,DESCRIPTION,[]
99993,[Used to treat inflammation of small areas of ...,"[{'is_selected': 0, 'passage_text': 'What is c...",what is a cortisone injection used for,679433,DESCRIPTION,[A cortisone injection is used to treat inflam...
99994,[(575) 527-1709],"[{'is_selected': 0, 'passage_text': '1 The Con...",fort selden roofing las cruces phone number,191150,NUMERIC,[]
99995,[255077833],"[{'is_selected': 0, 'passage_text': 'Complete ...",nasa credit union routing number,462353,NUMERIC,[255077833 is NASA's credit union routing numb...
99996,[Galveston County],"[{'is_selected': 0, 'passage_text': 'Most of t...",what county is hitchcock texas located in,607295,LOCATION,[]
99997,[All about great blowout style for about thirt...,"[{'is_selected': 0, 'passage_text': 'And with ...",what is blowout for hair,724819,DESCRIPTION,[]
99998,[No Answer Present.],"[{'is_selected': 0, 'passage_text': 'Isaac Bel...",what car does isaac bell drive in the wrecker,583161,ENTITY,[]
99999,"[Walrus, star fish, eel, crabs, jelly fish, an...","[{'is_selected': 1, 'passage_text': 'ANIMALS. ...",name some organisms that might live in a marin...,461916,ENTITY,"[Walrus, star fish, eel, crabs, jelly fish, an..."

In [10]:
df_train['answers'] = df_train['answers'].astype('str')
df['answers'] = df['answers'].astype('str')
# df_test['answers'] = df_test['answers'].astype('str')

KeyError: 'answers'

In [11]:
x =  df_train['answers'].str.contains('No Answer Present',na=False)

In [12]:
y = df['answers'].str.contains('No Answer Present',na=False)

In [ ]:
# z = df_test['answers'].str.contains('No Answer Present',na=False)

In [13]:
df_x = df_train[~x]

In [14]:
df_y = df[~y]

In [ ]:
# df_z = df_test[~z]

In [16]:
df_x

,answers,passages,query,query_id,query_type,wellFormedAnswers
0,['The immediate impact of the success of the m...,"[{'is_selected': 1, 'passage_text': 'The prese...",)what was the immediate impact of the success ...,1185869,DESCRIPTION,[]
1,['Restorative justice that fosters dialogue be...,"[{'is_selected': 0, 'passage_text': 'group dis...",_________ justice is designed to repair the ha...,1185868,DESCRIPTION,[]
10,['The reasons why Stalin wanted to control Eas...,"[{'is_selected': 0, 'passage_text': 'Western b...",why did stalin want control of eastern europe,1185854,DESCRIPTION,[]
100,['Nails rust in water because water allows the...,"[{'is_selected': 0, 'passage_text': 'what to D...",why do nails get rusty,1185755,DESCRIPTION,[]
1000,"['Depona Ab is a library in Vilhelmina, Sweden.']","[{'is_selected': 0, 'passage_text': 'A preview...",depona ab,1184773,DESCRIPTION,[]
100000,"['$43,746 for the 2014-2015 academic year.']","[{'is_selected': 0, 'passage_text': 'the cost ...",nyu tuition cost,467556,NUMERIC,[]
100001,['Before the age of 2–4 years.'],"[{'is_selected': 0, 'passage_text': 'In an eff...",at what age do kids start to hold memories,28213,NUMERIC,[]
100002,['Americans brush for just under the two minut...,"[{'is_selected': 0, 'passage_text': 'Your dent...",average teeth brushing time,44588,NUMERIC,[]
100003,"['Yes, funner is a word.']","[{'is_selected': 0, 'passage_text': 'Taken fro...",is funner a word?,410717,DESCRIPTION,[]
100005,"['An abbreviation of Conformite Conformité, eu...","[{'is_selected': 0, 'passage_text': 'CE Certif...",what is ce certified,728808,DESCRIPTION,[]
10001,['The customer support phone number of BancFir...,"[{'is_selected': 0, 'passage_text': 'Oklahoma ...",bancfirst customer service number,1174761,NUMERIC,[]
100011,"['DeWitt is located in Clinton County, Michiga...","[{'is_selected': 0, 'passage_text': 'DeWitt wa...",what county is dewitt michigan in?,605123,LOCATION,[]
100013,"[""A motorized oxygen mask doesn't qualify to m...","[{'is_selected': 1, 'passage_text': 'It might ...",using cpap without prescription,534802,DESCRIPTION,[]
100014,"[""It allows passengers to check-in to a flight...","[{'is_selected': 0, 'passage_text': 'A confirm...",what is early bird check in southwest,742216,ENTITY,[]
100016,['Bartholomew'],"[{'is_selected': 0, 'passage_text': 'WELCOME T...",what county is columbus city in,604568,LOCATION,[Columbus is a city in Bartholomew County.]
100017,['Social security administration in Bellevue W...,"[{'is_selected': 0, 'passage_text': 'Local soc...",social security administration in bellevue wa ...,499805,NUMERIC,[]
100018,['Yes whiskers are used to help balance as wel...,"[{'is_selected': 0, 'passage_text': 'Yes, whis...",are whiskers on cats used for balance,26191,DESCRIPTION,[]
100019,"['Shelton is in Fairfield County, Connecticut,...","[{'is_selected': 0, 'passage_text': 'My husban...","what county is shelton, ct",612660,LOCATION,[]
10002,"['Yes, the bachelor is legal.']","[{'is_selected': 0, 'passage_text': 'Arconic’s...",is the bachelor legal,1174759,DESCRIPTION,[]
100020,"['Average $111,082,']","[{'is_selected': 1, 'passage_text': 'Bp Americ...",what is BP level j salary,672511,NUMERIC,[]
100022,"[""DBA means 'Doing business as' is a term that...","[{'is_selected': 0, 'passage_text': 'In this p...",what dba mean,617187,DESCRIPTION,[]
100023,"['$4,625 per month.']","[{'is_selected': 1, 'passage_text': 'According...",average cost of assisted living in washington ...,33073,NUMERIC,[]
100025,['Chronic Obstructive Pulmonary Disease and So...,"[{'is_selected': 0, 'passage_text': 'Disabilit...",what disability is copd,620911,DESCRIPTION,[]
100027,['A contemporary Asian dish consisting of an o...,"[{'is_selected': 0, 'passage_text': 'In one co...",what is a omurice omelet,693333,DESCRIPTION,[An omurice omelet is a contemporary Asian dis...
100030,['A Jeep Compass Alternator Replacement is bet...,"[{'is_selected': 1, 'passage_text': 'The avera...",how much does it cost to change a jeep alternator,315061,NUMERIC,[The cost for a Jeep Compass Alternator Replac...
100031,['Crucial for proper brain function and plays ...,"[{'is_selected': 0, 'passage_text': 'Folate an...",what does folic acid do,637779,DESCRIPTION,[Folic acid is crucial for proper brain functi...
100033,['Pinellas County'],"[{'is_selected': 0, 'passage_text': '1 To chan...",what county is seminole fl in,612569,LOCATION,"[Seminole, Florida is in Pinellas County.]"
100034,['$4250'],"[{'is_selected': 0, 'passage_text': '1 A singl...",average cost dental implant,32055,NUMERIC,[The Average cost for Dental Implant is $4250.]
100035,['Yes'],"[{'is_selected': 1, 'passage_text': 'Big Bus T...",tripadvisor does the london hop on off bus pri...,524802,NUMERIC,[]
100036,['A ring of small red or skin-coloured bumps'],"[{'is_selected': 0, 'passage_text': 'Granuloma...",what does granuloma annulare look like,638438,DESCRIPTION,[]
...,...,...,...,...,...,...
9995,['The Eastern part of Texas is in the Central ...,"[{'is_selected': 0, 'passage_text': 'Central T...",is texas central time or eastern time,1174767,DESCRIPTION,[]
99951,"['Turkey, Lebanon, Syria, Jordan, and Israel.']","[{'is_selected': 1, 'passage_text': 'The count...",list of countries in eastern mediterranean region,440697,LOCATION,[]
99952,['A county island is an area of unincorporated...,"[{'is_selected': 1, 'passage_text': 'A county ...",what is an unincorporated island in a city,717553,LOCATION,[A county island is an area of unincorporated ...
99954,['Applied to a machine every time the operatin...,"[{'is_selected': 0, 'passage_text': 'Group Pol...",what group policies are applied,664606,DESCRIPTION,[Group policies are applied to a machine every...
99956,"['$61,230 per year. ']","[{'is_selected': 0, 'passage_text': 'An Execut...",how much does executive driector of family make,313785,NUMERIC,"[An executive director of a family makes $61,2..."
99959,['An explicit formula is a formula we can use ...,"[{'is_selected': 0, 'passage_text': 'explicit ...",what does explicit formula mean,637272,DESCRIPTION,[]
99960,"['No, it is a city.']","[{'is_selected': 0, 'passage_text': 'Memphis S...",is memphis a state,417820,DESCRIPTION,[]
99963,['Completely Automated Public Turing Test to T...,"[{'is_selected': 0, 'passage_text': 'Freebase(...",what does the acronym captcha stand for,649330,DESCRIPTION,[The acronym CAPTCHA stands for Completely Aut...
99965,"['No, it is GMT/UTC - 6h during Standard Time ...","[{'is_selected': 0, 'passage_text': 'Central S...",is chicago cst time,406079,DESCRIPTION,[]
99966,"['Rodents, fish, crustaceans, amphibians, and ...","[{'is_selected': 0, 'passage_text': 'Mink trac...",what do mink eat,623976,ENTITY,"[Mink eats rodents, fish, crustaceans, amphibi..."
99967,['Schizophrenia or suicidal behavior.'],"[{'is_selected': 1, 'passage_text': 'Clozapine...",clozapine interacts with what pain medication,93621,ENTITY,[]
99968,['Feel worthless and hopeless'],"[{'is_selected': 0, 'passage_text': 'Do one bi...",what happens when someone heart is broken,667354,DESCRIPTION,[]
9997,"['Yes, Charles Bronson is dead.']","[{'is_selected': 0, 'passage_text': 'After mov...",is the actor charles bronson dead,1174765,PERSON,[]
99972,['Yes'],"[{'is_selected': 0, 'passage_text': 'He was th...",was william henry harrison a republican,541259,DESCRIPTION,[]
99973,"['Fairbury is in Livingston County, Illinois.']","[{'is_selected': 1, 'passage_text': '407 Walnu...",what county is fairbury il,605770,LOCATION,[]
99977,"['11 pounds', '22-50 pounds']","[{'is_selected': 0, 'passage_text': 'Rated 4 o...",weight evenflo maestro,547249,NUMERIC,[The weight of Evenflo Maestro is 11 pounds.]
9998,"['Yes, iPad Pro is water resistant.']","[{'is_selected': 0, 'passage_text': 'Apple's n...",is the apple ipad water resistant?,1174764,DESCRIPTION,[]
99981,['908 kWh'],"[{'is_selected': 1, 'passage_text': 'The avera...",average kwh per household in us,38107,NUMERIC,[]
99985,"['Yes, Luxury vinyl flooring is a diy job.']","[{'is_selected': 1, 'passage_text': 'Luxury vi...",is vinyl flooring a diy job,430897,DESCRIPTION,[]
99986,['A floating museum is in New York City.'],"[{'is_selected': 1, 'passage_text': 'Intrepid ...",what city is a floating museum,595815,LOCATION,[]
99988,"['Carbon dioxide, methane and other greenhouse...","[{'is_selected': 1, 'passage_text': 'Global wa...",what causes the greenhouse effect,592625,DESCRIPTION,[]
9999,"['Yes, the asthenosphere made of iron and nick...","[{'is_selected': 1, 'passage_text': 'The asthe...",is the asthenosphere made of iron and nickel,1174763,DESCRIPTION,[]
99991,['Amuse means keeping yourself or someone else...,"[{'is_selected': 0, 'passage_text': 'Much late...",the definition of amuse,515137,DESCRIPTION,[]
99992,"['WBC is 5 to 10 K/uL, HGB is 12 to 17.4 g/dL.']","[{'is_selected': 0, 'passage_text': 'A complet...",what is human blood value on a cbc,756122,DESCRIPTION,[]
99993,['Used to treat inflammation of small areas of...,"[{'is_selected': 0, 'passage_text': 'What is c...",what is a cortisone injection used for,679433,DESCRIPTION,[A cortisone injection is used to treat inflam...
99994,['(575) 527-1709'],"[{'is_selected': 0, 'passage_text': '1 The Con...",fort selden roofing las cruces phone number,191150,NUMERIC,[]
99995,['255077833'],"[{'is_selected': 0, 'passage_text': 'Complete ...",nasa credit union routing number,462353,NUMERIC,[255077833 is NASA's credit union routing numb...
99996,['Galveston County'],"[{'is_selected': 0, 'passage_text': 'Most of t...",what county is hitchcock texas located in,607295,LOCATION,[]
99997,['All about great blowout style for about thir...,"[{'is_selected': 0, 'passage_text': 'And with ...",what is blowout for hair,724819,DESCRIPTION,[]
99999,"['Walrus, star fish, eel, crabs, jelly fish, a...","[{'is_selected': 1, 'passage_text': 'ANIMALS. ...",name some organisms that might live in a marin...,461916,ENTITY,"[Walrus, star fish, eel, crabs, jelly fish, an..."

In [17]:
df_y

,answers,passages,query,query_id,query_type,wellFormedAnswers
0,['A corporation is a company or group of peopl...,"[{'is_selected': 0, 'passage_text': 'A company...",. what is a corporation?,1102432,DESCRIPTION,[]
1,['Rachel Carson writes The Obligation to Endur...,"[{'is_selected': 0, 'passage_text': 'Read to w...",why did rachel carson write an obligation to e...,1102431,DESCRIPTION,[]
10000,['The symptoms of a dying mouse are runny eyes...,"[{'is_selected': 0, 'passage_text': 'This can ...",symptoms of a dying mouse,1090282,ENTITY,[]
100000,"['Globally 8,640,000 lightning strikes per day.']","[{'is_selected': 0, 'passage_text': 'Lightning...",average number of lightning strikes per day,39449,NUMERIC,[]
100001,"['Yes, over fertilizing can burn lawn.']","[{'is_selected': 0, 'passage_text': 'Verify th...",can you burn your lawn with fertilizer,76162,DESCRIPTION,[]
100007,['The meaning of the name Goch is red.'],"[{'is_selected': 0, 'passage_text': 'See the G...",goch meaning,195512,DESCRIPTION,[]
10001,['acidic and extremely painful is symptom of a...,"[{'is_selected': 0, 'passage_text': 'Pain from...",symptoms of a gastric ulcer in women,1090280,ENTITY,[]
100010,['For anxiety treatment is 1 mg two to three t...,"[{'is_selected': 0, 'passage_text': 'Pdoc gave...",how often can ativan be taken,331318,NUMERIC,[]
100012,['William Bradford served thirty years as Gove...,"[{'is_selected': 0, 'passage_text': 'Added 201...",how many years did william bradford serve as g...,300674,NUMERIC,[]
100013,"['2,662']","[{'is_selected': 0, 'passage_text': 'City of A...",albany mn population,15177,NUMERIC,"[The population of Albany, Minnesota is 2,662. ]"
100015,"['It means preventing, hindering, or acting as...","[{'is_selected': 1, 'passage_text': 'Adjective...",define preventive,125705,DESCRIPTION,[]
100017,"['An infection, heredity or an abnormality of ...","[{'is_selected': 0, 'passage_text': 'Achalasia...",causes of achalasia,85224,DESCRIPTION,[]
100019,['The Volcano forecast for Apr 12 is 52 degree...,"[{'is_selected': 1, 'passage_text': 'Volcano 1...","current weather in volcano, ca",114414,DESCRIPTION,[The Volcano forecast for Apr 12 is 52 degrees...
100024,['6 to 10 days'],"[{'is_selected': 0, 'passage_text': 'Symptoms ...",how many days after ovulation can i tell i'm p...,280709,NUMERIC,[]
100026,['The cost of a first-class postage stamp is n...,"[{'is_selected': 0, 'passage_text': 'The idea ...",how much are postage stamps right now,302299,NUMERIC,[]
100028,['A great way to add a touch of color without ...,"[{'is_selected': 0, 'passage_text': 'Changing ...",color overlay photoshop,94798,DESCRIPTION,[]
10003,['High air pollution levels can cause immediat...,"[{'is_selected': 0, 'passage_text': 'Long-term...",symptoms of air pollution exposure,1090278,ENTITY,[]
100031,['It has a mild humid temperate climate with w...,"[{'is_selected': 0, 'passage_text': 'The clima...",average temperature cardiff wales,44932,NUMERIC,[]
100036,['The highest paying subspecialty in orthopedi...,"[{'is_selected': 0, 'passage_text': 'This sala...",highest paying subspecialty in orthopedics,202671,ENTITY,[]
100037,['Hippocrates'],"[{'is_selected': 0, 'passage_text': 'Hippocrat...",____________________ is considered the father ...,9083,DESCRIPTION,[Hippocrates is considered the father of moder...
100044,['Yes'],"[{'is_selected': 0, 'passage_text': 'How long ...",does xpress bet charge to deposit money in you...,174249,DESCRIPTION,[]
100047,['The distance from Faribault to Winona is 95M...,"[{'is_selected': 0, 'passage_text': 'Winona, M...",how far is faribault from winona?,230982,NUMERIC,[]
100048,['120 days from the date of the Note.'],"[{'is_selected': 0, 'passage_text': 'New and U...",how many days is an appraisal good for a fanni...,281439,NUMERIC,[An appraisal is good for 120 days from the da...
100049,['The CRM/Outlook synchronization process can ...,"[{'is_selected': 0, 'passage_text': 'Dynamics ...",dynamics crm outlook synchronization process,177008,DESCRIPTION,[]
10005,"[""The symptoms of an intolerance to barley are...","[{'is_selected': 0, 'passage_text': 'Just like...",symptoms of an intolerance to barley,1090275,ENTITY,[]
100050,['Wisdom teeth recovery time is three to four ...,"[{'is_selected': 1, 'passage_text': 'You shoul...",how long to recover from wisdom teeth removal,271872,NUMERIC,[]
100051,"['From $26,000 to $39,000 a year']","[{'is_selected': 0, 'passage_text': 'If you ar...",average pharmacy tech salary,40287,NUMERIC,[The average salary for a pharmacy technician ...
100052,['1 Skin care: For a clearer complexion and to...,"[{'is_selected': 1, 'passage_text': 'Major Ben...",benefits of lymphatic drainage facial,50983,DESCRIPTION,[]
10006,['The symptoms of Urinary tract infection is b...,"[{'is_selected': 0, 'passage_text': 'Women may...",symptoms of an uti sensation,1090274,ENTITY,[]
100061,"[""Half of the country's Spanish-speakers resid...","[{'is_selected': 0, 'passage_text': 'Spanish l...",english is the official state language in some...,180613,ENTITY,[]
...,...,...,...,...,...,...
99936,['$48.00'],"[{'is_selected': 1, 'passage_text': '1 A heart...",how much does it cost for dog to be tested for...,314458,NUMERIC,[The cost for dog to be tested for heartworms ...
99939,"['$52,000']","[{'is_selected': 1, 'passage_text': 'The avera...",average salary for college grad,42212,NUMERIC,[The average salary for a college graduate is ...
9994,['The symptoms of Ancylostomiasis include rash...,"[{'is_selected': 0, 'passage_text': 'Symptoms ...",symptoms ancylostomiasis,1090288,ENTITY,[]
99941,['Moisture should penetrate to about 6 to 8 in...,"[{'is_selected': 0, 'passage_text': 'Knowing h...",how to properly water your grass,373938,DESCRIPTION,[]
99944,['A membrane-bound compartment or structure in...,"[{'is_selected': 0, 'passage_text': 'However, ...",cell organelles definition,89573,DESCRIPTION,[Cell organelles is a membrane bound compartme...
99946,"['Yes, bactrim work to treat diverticulitis.']","[{'is_selected': 0, 'passage_text': 'If the pa...",does bactrim work to treat diverticulitis,163622,DESCRIPTION,[]
99948,"['Yes,Rosacea is a facial skin condition that ...","[{'is_selected': 0, 'passage_text': 'By Mayo C...",does adult acne rosacea give you blepharitis,162662,DESCRIPTION,[]
99949,['Yes'],"[{'is_selected': 0, 'passage_text': 'It turns ...",do gemstones have thermal properties,156436,DESCRIPTION,[]
9995,"['Symptoms of hemothorax include: chest pain, ...","[{'is_selected': 1, 'passage_text': 'Symptoms ...",symptoms and signs of massive hemothorax,1090287,ENTITY,[]
99953,['One-thousanth'],"[{'is_selected': 0, 'passage_text': '1 To conv...",how many milliliters are in a meter?,289301,NUMERIC,[There are one thousand milliliters in a meter.]
99954,"['Mastication, taste, deglutition, articulatio...","[{'is_selected': 0, 'passage_text': 'Tongue an...",function of tongue,192540,DESCRIPTION,"[The function of the tongue is mastication, ta..."
99960,['Generally 10 months'],"[{'is_selected': 0, 'passage_text': 'Homepage ...",how many months in a university academic year,289922,NUMERIC,[There are generally 10 months in a university...
99963,['One millimeter of length converted to micron...,"[{'is_selected': 0, 'passage_text': 'Convertin...",convert microns to millimeters,98729,NUMERIC,[One millimeter of length converted to micron ...
99967,['It refers to electronic harassment or bullyi...,"[{'is_selected': 1, 'passage_text': 'Cyberbull...",cyber harassment definition,114698,DESCRIPTION,[]
99969,['Ginger has long been used in Asia to treat m...,"[{'is_selected': 0, 'passage_text': 'Cesar’s A...",how to keep a dog from getting motion sickness,366060,DESCRIPTION,[]
9997,['Symptoms of perimenopause may include: irreg...,"[{'is_selected': 0, 'passage_text': 'Perimenop...",symptoms for premenopausal,1090285,ENTITY,[]
99975,['About 12 minutes.'],"[{'is_selected': 0, 'passage_text': '{{model.a...",how long do you cook a hard boiled egg,247441,NUMERIC,[]
99977,['It is recommended that you take a practice n...,"[{'is_selected': 1, 'passage_text': 'Oklahoma ...",how to become a notary oklahoma,345237,DESCRIPTION,[It is recommended that you take a practice no...
9998,['The symptoms of gallbladder attack include r...,"[{'is_selected': 0, 'passage_text': 'CT scan m...",symptoms gallbladder attack,1090284,ENTITY,[]
99982,['25-26 minutes.'],"[{'is_selected': 0, 'passage_text': '1 Top wit...",how long do you bake muffins,247194,NUMERIC,[]
99985,['$2 to $5 per square foot.'],"[{'is_selected': 0, 'passage_text': 'Vinyl, ac...",cost per foot on hardy plank installation,108172,NUMERIC,[]
99986,['$ 50 to $ 200'],"[{'is_selected': 1, 'passage_text': 'according...",how much does a pap smear cost,310713,NUMERIC,[]
99987,['1 to 2 days.'],"[{'is_selected': 0, 'passage_text': 'When I wa...",how long does it take to mail a card usps,257688,NUMERIC,[]
99988,['The meaning of glioma is a tumor springing f...,"[{'is_selected': 0, 'passage_text': 'Optic Gli...",glioma meaning,195199,DESCRIPTION,[]
9999,['The symptoms of a bad rear main seal are sli...,"[{'is_selected': 0, 'passage_text': 'If you di...",symptoms of a bad main seal,1090283,ENTITY,[]
99990,"['Pizza, pasta and ice cream.']","[{'is_selected': 0, 'passage_text': 'Kashmiri ...",different types of cuisines,150337,DESCRIPTION,[]
99992,"['Yes, electric cleansers are safe.']","[{'is_selected': 0, 'passage_text': 'Features ...",are electric cleansers safe?,22241,DESCRIPTION,[]
99995,"['It is defined as the quality of being wide, ...","[{'is_selected': 0, 'passage_text': '1 The sta...",define width,129177,NUMERIC,[]
99996,['Human Resource Management is the term used t...,"[{'is_selected': 1, 'passage_text': 'Human Res...",forbes definition of human resource management,190655,DESCRIPTION,[]
99999,['List the elements you want to include in a h...,"[{'is_selected': 0, 'passage_text': 'Business ...",how to offer health insurance to employees,371455,DESCRIPTION,[]

In [25]:
df_train[df_train['query_id'] == 281922]

Empty DataFrame
Columns: [answers, passages, query, query_id, query_type, wellFormedAnswers]
Index: []

In [26]:
df[df['query_id'] == 281922]

Empty DataFrame
Columns: [answers, passages, query, query_id, query_type, wellFormedAnswers]
Index: []

In [30]:
df_test[df_test['query_id'] == 120233]

,passages,query,query_id,query_type
100004,[{'passage_text': 'Dew Point Temperature (Td)....,define dew point.,120233,DESCRIPTION

In [42]:
df_test.shape[0]

101092

In [41]:
df_test.shape[0] - eval_.shape[0]

90675

In [61]:
eval_ = df_test[df_test['query_id'].isin(list(test['query_id'].unique()))]

In [15]:
train_list  = d

2

In [18]:
test = pd.read_csv('./eval1_unlabelled.tsv',delimiter='\t',names=test_header)

In [34]:
test.shape[0]/10

10417.0

In [62]:
df_combined = pd.concat([df_x,df_y])

In [63]:
df_combined.shape

(559006, 6)

In [65]:
df_combined_query = df_combined['query']

In [68]:
sorted_train_query = sorted_train_data['query']

In [72]:
s1 = set(df_combined_query)

In [73]:
s2 = set(sorted_train_query)

In [75]:
s3 = s1.intersection(s2)

In [82]:
s4 = set(test_query)

In [83]:
s1.intersection(s4)

set()

In [80]:
test_query = test['query']

In [84]:
gold_dataset = s1-s2

In [ ]:
df_com

In [89]:
last_training_ds = df_combined[df_combined['query'].isin(gold_dataset)]

In [90]:
last_training_ds

,answers,passages,query,query_id,query_type,wellFormedAnswers
100089,['Social security disability insurance benefit...,"[{'is_selected': 0, 'passage_text': 'Beneficia...",different types of social security disability,150905,DESCRIPTION,[]
100093,['One-third of France’s land is crop growing. ...,"[{'is_selected': 1, 'passage_text': 'One-third...",what does france grow and produce,637862,DESCRIPTION,[]
100126,['It is located at the address 1304 Ne Cedar S...,"[{'is_selected': 0, 'passage_text': 'United St...",united states postal service roseburg or,532464,DESCRIPTION,[]
100163,['Flooring contractors will always add labor c...,"[{'is_selected': 0, 'passage_text': 'Step 1. E...",installation cost,396483,NUMERIC,[]
100171,['Yes'],"[{'is_selected': 0, 'passage_text': 'Marsala N...",is marsala like madeira,417427,DESCRIPTION,[]
100232,['A relatively common type of hemolytic diseas...,"[{'is_selected': 1, 'passage_text': 'ABO incom...",what is abo incompatibility in newborn,707064,DESCRIPTION,[ABO incompatibility is a common type of hemol...
100241,"[""VanDevere Kia is celebrating America's Indep...","[{'is_selected': 0, 'passage_text': 'Kia Fourt...",kia sales for july,434314,NUMERIC,[]
100271,"[""The Vitamix XL 5201 blender includes two jar...","[{'is_selected': 0, 'passage_text': 'Blend hot...",vitamix xl,537979,DESCRIPTION,[]
100285,['26 inches Two-Stage Snow Thrower 208cc Troy-...,"[{'is_selected': 0, 'passage_text': 'The Troy-...",what engine on troy bilt snow blowers?,657386,ENTITY,[]
100370,['Two convenient locations in Sioux Falls are ...,"[{'is_selected': 0, 'passage_text': 'Start fro...",sioux falls wireless world,498676,DESCRIPTION,[]
100376,['The political background of Europe at the ti...,"[{'is_selected': 1, 'passage_text': 'Causes of...",cause of failure of league of nation,84320,DESCRIPTION,[]
100388,['A 150-g serving of boiled red potatoes has a...,"[{'is_selected': 1, 'passage_text': 'A 150-g s...",glycemic index potatoes vs rice,195372,NUMERIC,[]
100448,"['Forceful rubbing or friction on the foot, bo...","[{'is_selected': 0, 'passage_text': 'Running D...",what cause random foot blister when there was ...,583942,DESCRIPTION,[]
100454,['Allscripts was first to market with electron...,"[{'is_selected': 0, 'passage_text': '** Clinic...",what is allscripts?,709679,DESCRIPTION,[]
100455,"['Push ups works the stomach, arms, chest, and...","[{'is_selected': 1, 'passage_text': 'Here is a...",what does push ups work,646492,DESCRIPTION,[]
10046,"['No, the y in enjoy is not a consonant becaus...","[{'is_selected': 0, 'passage_text': 'The vowel...",is the y in enjoy a consonant,1174713,DESCRIPTION,[]
100470,"['No,It means you have to refuse to testify.',...","[{'is_selected': 0, 'passage_text': 'In a civi...",does a subpoena mean you have to testify,162436,DESCRIPTION,[]
100501,"['Approximately 4 years or 40,000 miles.', 'Ev...","[{'is_selected': 0, 'passage_text': 'Related Q...",how often to change serpentine belt,332625,NUMERIC,[The serpentine belt should change after appro...
100518,['Yes'],"[{'is_selected': 1, 'passage_text': 'In buildi...",is an HVAC plenum necessary,402377,DESCRIPTION,[]
100577,"['Marion County', 'Marion, Washington, Clinton...","[{'is_selected': 0, 'passage_text': 'DHS Offic...",what county is centralia illinois,604096,LOCATION,"[Centralia is in Marion County, Illinois.]"
100587,"['Yes, it is hormone progesterone that can aff...","[{'is_selected': 1, 'passage_text': 'Also have...",can constipation be period related,65983,DESCRIPTION,[]
100592,"['John F. Kennedy, Donald J. Trump']","[{'is_selected': 1, 'passage_text': 'Other pre...",us presidents who forgo salary,534096,PERSON,[]
100606,"[""American meaning of it is 'Strong, the gift ...","[{'is_selected': 1, 'passage_text': 'The name ...",what does the name Ethan mean,650927,DESCRIPTION,[]
100651,['An ideogram that conveys its meaning through...,"[{'is_selected': 0, 'passage_text': 'Numerolog...",pictographs definition,475306,DESCRIPTION,[An ideogram that conveys its meaning through ...
100666,['Jerusalem.'],"[{'is_selected': 1, 'passage_text': 'Jerusalem...",what city is sacred to three monotheistic reli...,596133,LOCATION,[]
100691,['The Artero is a unique exotic sports car des...,"[{'is_selected': 0, 'passage_text': 'Artero Cu...",what is artero,719894,DESCRIPTION,[]
100700,"['It is located at 11532 Page Service Drive, S...","[{'is_selected': 0, 'passage_text': 'Start you...",us bank location maryland,533494,LOCATION,[]
100713,"[""Disney's BoardWalk Inn, Disney's All-Star Mo...","[{'is_selected': 1, 'passage_text': 'Disney's ...",what are the select walt disney world resort h...,573394,PERSON,[]
100753,['Jaw pain and TMJ symptoms include: 1 atypica...,"[{'is_selected': 0, 'passage_text': 'Below are...",symptoms of jaw and eye pain,508055,ENTITY,[]
100758,['That will take all of the files and copy it ...,"[{'is_selected': 0, 'passage_text': 'don't be ...",what is extract all on my computer,745899,DESCRIPTION,[]
...,...,...,...,...,...,...
99177,"[""Argon is a noble gas that comprises 0.93% of...","[{'is_selected': 0, 'passage_text': 'Coravin M...",difference between nitrogen and argon,148081,DESCRIPTION,[]
99185,['cause of proteinuria is diabetes and kidney...,"[{'is_selected': 1, 'passage_text': 'People wi...",cause of proteinuria,84487,DESCRIPTION,[]
99202,"['Chamomile tea, rub the gel of aloe vera on t...","[{'is_selected': 1, 'passage_text': 'Chamomile...",home remedies for gum disease,204537,ENTITY,[]
9930,"['The symptoms of strep throat are sore, red t...","[{'is_selected': 0, 'passage_text': 'The strep...",strep symptoms of the body,1090365,ENTITY,[]
99301,"['Botulism symptoms are weakness, trouble seei...","[{'is_selected': 0, 'passage_text': 'Although ...",botulism symptoms diagnosis and treatment,55682,ENTITY,[]
99337,['Yes'],"[{'is_selected': 0, 'passage_text': 'The chara...",does is snow in haw,167674,DESCRIPTION,[]
99355,[''],"[{'is_selected': 0, 'passage_text': 'Worldwide...",how does pollution increase human population,227261,DESCRIPTION,[]
99385,"[""Death's Head unit which eventually made up t...","[{'is_selected': 0, 'passage_text': 'Totenkopf...",death head units definition,116095,DESCRIPTION,[]
99408,"[""It is affirms Belmont's status as one of the...","[{'is_selected': 0, 'passage_text': 'Curb Even...",curb event center,113649,DESCRIPTION,[]
99444,"['Cinnamon, Sprinkle, Prickly Pear/ Nopal, Gra...","[{'is_selected': 0, 'passage_text': 'Too much ...",foods and supplements to lower blood sugar,188714,ENTITY,[]
99477,"['Apply baking soda to your pimples,Toothpaste...","[{'is_selected': 0, 'passage_text': 'Lemon jui...",home remedies for pimples,204579,DESCRIPTION,[]
99481,"['Testing To Early, not reading your urine pre...","[{'is_selected': 1, 'passage_text': 'One cause...",causes of false negative pregnancy test,86437,DESCRIPTION,[]
99510,['It is the result of an irreversible process ...,"[{'is_selected': 0, 'passage_text': 'A dissipa...",define dissipation,120451,DESCRIPTION,[Dissipation is defined as the act of scatteri...
99513,"['Trigger finger, hyperextension, long periods...","[{'is_selected': 0, 'passage_text': 'Wrist, Ha...",causes for fingers to hurt,84841,DESCRIPTION,[]
99529,['Biggest black sea bass caught by Edward Llew...,"[{'is_selected': 1, 'passage_text': '1903, The...",edward llewellyn largest black bass caught,178136,NUMERIC,[]
9954,['Side Effects of sulfasalazine rheumatoid art...,"[{'is_selected': 0, 'passage_text': 'Several p...",sulfasalazine rheumatoid arthritis side effects,1090333,DESCRIPTION,[]
99567,['Scintilla Aiste Gramantaite was born and rai...,"[{'is_selected': 1, 'passage_text': 'Aiste Gra...",actress who born at litrhuania,10945,PERSON,[]
99603,['The difference between a state and a nation ...,"[{'is_selected': 0, 'passage_text': 'Answers. ...",difference between nation and state and nation...,148037,DESCRIPTION,[]
99657,"['Eat nutrient-rich healthy foods, macaroni an...","[{'is_selected': 0, 'passage_text': 'You know ...",foods that enhance appetite,189359,ENTITY,[]
99679,['Rice and Potatoes.'],"[{'is_selected': 0, 'passage_text': 'Certain f...",foods that help cramps,189467,ENTITY,[]
99683,"['Generic Adderall,Adderall XR']","[{'is_selected': 0, 'passage_text': 'Generic (...",different brands of adderall,149686,ENTITY,[]
99713,"['To become a registered nurse, you need to en...","[{'is_selected': 0, 'passage_text': 'A: To bec...",do i need to go to collage to become a rn nurse,157068,DESCRIPTION,"[Yes, you need to go to collage to become a re..."
99731,['Ocular Migraine and minor irritation.'],"[{'is_selected': 0, 'passage_text': 'Introduct...",bright light in eyes symptoms,56353,ENTITY,[]
99773,['Gross salary is the term used to describe al...,"[{'is_selected': 0, 'passage_text': 'Basic Def...",definition of gross salary verus basic salary,135030,NUMERIC,[]
99799,"['The side plank exercise,By Zero Belly Diet,a...","[{'is_selected': 0, 'passage_text': 'Once you ...",how to reduce belly fat?,375184,DESCRIPTION,[]
99807,['A scapula fracture and subscapularis muscle ...,"[{'is_selected': 0, 'passage_text': 'Left shou...",causes of back left shoulder blade pain,85449,DESCRIPTION,[]
99825,"['$72,747.']","[{'is_selected': 0, 'passage_text': 'The avera...",average salary financial analyst dallas,41904,NUMERIC,[]
99828,['More than 1 million in 190 countries'],"[{'is_selected': 1, 'passage_text': 'Most VRBO...",how many places does homeaway offer,293271,NUMERIC,[]
99900,"['Dry mouth, Eyes stop making tears, Sweating ...","[{'is_selected': 0, 'passage_text': 'Here are ...",common signs and symptoms of dehydration,95786,ENTITY,[]
99969,['Ginger has long been used in Asia to treat m...,"[{'is_selected': 0, 'passage_text': 'Cesar’s A...",how to keep a dog from getting motion sickness,366060,DESCRIPTION,[]

In [99]:
last_training_ds.iloc[12]['passages']

[{'is_selected': 0,
  'passage_text': "Running Doc: To avoid blisters get the proper shoes...socks...insoles...ointment...orthotics. The Running Doc’s advice on how to avoid blisters includes selecting the proper running shoe. Make sure it fits! Every time I run long distances, I get blisters all over my feet and in between my toes. I have tried socks with different thicknesses and Vaseline, and just about everything. Doc, I need your help to stop these blisters! I am running the ING NYC Marathon and don't want to be a mess after the race!",
  'url': 'http://www.nydailynews.com/sports/more-sports/proper-shoes-socks-insoles-orthotics-runners-avoid-blisters-article-1.1499112'},
 {'is_selected': 0,
  'passage_text': 'If there is an infection present, you may see that your blister has filled with pus and is yellowish or greenish in color. Medical conditions such as dyshidrosis (a form of eczema), herpes, and chickenpox can also cause blisters on one’s feet. Blisters are very common among athletes.',
  'url': 'http://www.footvitals.com/skin/blisters.html'},
 {'is_selected': 0,
  'passage_text': 'Blisters are often annoying, painful, or uncomfortable. In most cases, they are not a symptom of anything serious and will heal without any medical intervention. Some infections can cause skin blistering that requires treatment. And in rare cases a skin condition may produce blisters.',
  'url': 'http://www.healthline.com/health/blisters'},
 {'is_selected': 0,
  'passage_text': 'In my experience, the most common type are blisters on feet. These painful fluid-filled sacs are the result of increased temperatures that make your feet sweat and swell. This causes rubbing against your shoes, even the comfortable ones.',
  'url': 'https://www.bodyglide.com/blisters-on-feet-causes/'},
 {'is_selected': 0,
  'passage_text': 'Generally blisters may be caused by: 1  Friction - the most common cause in the feet. 2  Direct damage to the skin by corrosive substances or heat. 3  Some infectious diseases (for example, chickenpox). 4  Some inherited diseases (for example, pompholyx).',
  'url': 'https://patient.info/health/foot-blisters'},
 {'is_selected': 0,
  'passage_text': 'Blisters are most common on the feet and ankles, as these are the areas most subject to heat and pressure in most people. Generally blisters may be caused by: Friction - the most common cause in the feet. Direct damage to the skin by corrosive substances or heat. Some infectious diseases (for example, chickenpox).',
  'url': 'https://patient.info/health/foot-blisters'},
 {'is_selected': 0,
  'passage_text': 'In addition to medication for the infection, your doctor may be able to give you something to treat the symptoms. If there is a known cause for the blisters, such as contact with a certain chemical or use of a drug, use of that product should be discontinued.',
  'url': 'http://www.healthline.com/health/blisters'},
 {'is_selected': 0,
  'passage_text': 'Friction occurs when something rubs against your skin for a prolonged period of time. This happens most commonly on hands and feet. Contact dermatitis can also cause blisters. This is a skin reaction to allergens, like poison ivy, latex, adhesives, or irritants like chemicals or pesticides.',
  'url': 'http://www.healthline.com/health/blisters'},
 {'is_selected': 1,
  'passage_text': 'The fluid inside a blister is called serum or plasma. This fluid is usually clear, but it can also be red if the blister is filled with blood, or yellowish green if it is filled with pus, indicating an infection. Blisters may appear on one foot or both feet, and they do not discriminate based on gender, age, or race. Blisters on feet can be caused by numerous things, including: Forceful rubbing or friction on the foot. Bone spurs or exostoses.',
  'url': 'http://www.footvitals.com/skin/blisters.html'},
 {'is_selected': 1,
  'passage_text': 'Narrow shoes can cause blisters on the big toe and little toe. A shallow toe box can lead to blisters on the tops of the toes, while loose shoes can create blisters on the tips of the toes. * When trying on shoes, be sure to wear the same socks, insoles, or orthotics that you wear when training or racing.',
  'url': 'http://www.nydailynews.com/sports/more-sports/proper-shoes-socks-insoles-orthotics-runners-avoid-blisters-article-1.1499112'}]

In [156]:
rows = []

In [153]:
last_training_ds['passages_length'] = last_training_ds.apply(lambda row : len(row['passages']),axis=1)

/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [154]:
last_training_ds['passages_length']

100089    10
100093    10
100126     6
100163    10
100171    10
100232    10
100241     8
100271    10
100285    10
100370     8
100376    10
100388    10
100448    10
100454    10
100455    10
10046     10
100470    10
100501    10
100518    10
100577    10
100587    10
100592    10
100606    10
100651    10
100666    10
100691    10
100700     9
100713    10
100753    10
100758    10
          ..
99177     10
99185     10
99202     10
9930      10
99301     10
99337     10
99355     10
99385     10
99408      7
99444     10
99477     10
99481     10
99510     10
99513     10
99529      9
9954      10
99567     10
99603     10
99657     10
99679     10
99683     10
99713     10
99731     10
99773     10
99799     10
99807     10
99825      6
99828      7
99900     10
99969     10
Name: passages_length, Length: 34818, dtype: int64

In [107]:
last_training_ds.shape

(34818, 6)

In [157]:
new_bhokal_df = last_training_ds.apply(lambda row : create_df(row),axis=1)

In [158]:
new_bhokal_df = pd.DataFrame(rows)

In [159]:
query_count = new_bhokal_df.groupby('query_id').agg('count')

In [160]:
query_count = query_count.reset_index()

In [161]:
query_count

       query_id  label  passage_id  passage_text  query
0            49     10          10            10     10
1           202     10          10            10     10
2           362     10          10            10     10
3           374     10          10            10     10
4           446     10          10            10     10
5           484     10          10            10     10
6           514     10          10            10     10
7           623     10          10            10     10
8           797     10          10            10     10
9           857     10          10            10     10
10          919     10          10            10     10
11          990     10          10            10     10
12         1135     10          10            10     10
13         1211     10          10            10     10
14         1231     10          10            10     10
15         1251     10          10            10     10
16         1272     10          10            10     10
17         1325     10          10            10     10
18         1369     10          10            10     10
19         1493     10          10            10     10
20         1579     10          10            10     10
21         1787     10          10            10     10
22         1862     10          10            10     10
23         1920     10          10            10     10
24         2057     10          10            10     10
25         2337     10          10            10     10
26         2358     10          10            10     10
27         2420     10          10            10     10
28         2458     10          10            10     10
29         2503     10          10            10     10
...         ...    ...         ...           ...    ...
28718   1184626     10          10            10     10
28719   1184629     10          10            10     10
28720   1184631     10          10            10     10
28721   1184637     10          10            10     10
28722   1184642     10          10            10     10
28723   1184647     10          10            10     10
28724   1184650     10          10            10     10
28725   1184658     10          10            10     10
28726   1184659     10          10            10     10
28727   1184660     10          10            10     10
28728   1184813     10          10            10     10
28729   1184869     10          10            10     10
28730   1184906     10          10            10     10
28731   1185153     10          10            10     10
28732   1185196     10          10            10     10
28733   1185262     10          10            10     10
28734   1185390     10          10            10     10
28735   1185400     10          10            10     10
28736   1185425     10          10            10     10
28737   1185466     10          10            10     10
28738   1185478     10          10            10     10
28739   1185516     10          10            10     10
28740   1185543     10          10            10     10
28741   1185558     10          10            10     10
28742   1185580     10          10            10     10
28743   1185631     10          10            10     10
28744   1185661     10          10            10     10
28745   1185698     10          10            10     10
28746   1185702     10          10            10     10
28747   1185828     10          10            10     10

[28748 rows x 5 columns]

In [162]:
query_count[query_count['query']!=10]

Empty DataFrame
Columns: [query_id, label, passage_id, passage_text, query]
Index: []

In [165]:
import pickle

In [166]:
rfile = open('new_bhokal_df','wb')

In [167]:
pickle.dump(new_bhokal_df,rfile)

In [143]:
new_bhokal_df.shape

(339417, 5)

In [110]:
new_df = pd.DataFrame(rows)

In [115]:
 label_count = new_df.groupby('query_id').agg({'label' : sum})

In [117]:
label_count = label_count.reset_index()

In [127]:
kaam_ki_query_ids = label_count[label_count['label'].isin([1,2])]['query_id']

In [ ]:
new_final_df = new_df[new]

In [108]:
new_df = pd.DataFrame rows

{'query_id': 150905,
 'query': 'different types of social security disability',
 'label': 0,
 'passage_text': 'Beneficiary data. The following briefly describes the different types of beneficiaries paid by Social Security. The descriptions are not meant to be definitive. Check with a local Social Security office if you believe you may be eligible for benefits. We pay benefits to the following types of beneficiaries.'}

In [103]:
rows

[{'query_id': 150905,
  'query': 'different types of social security disability',
  'label': 0,
  'passage_text': 'Beneficiary data. The following briefly describes the different types of beneficiaries paid by Social Security. The descriptions are not meant to be definitive. Check with a local Social Security office if you believe you may be eligible for benefits. We pay benefits to the following types of beneficiaries.'},
 {'query_id': 150905,
  'query': 'different types of social security disability',
  'label': 0,
  'passage_text': "A: We tend to think of Social Security benefits as going just to retired workers. But the more than 59 million Americans who receive monthly payments from Social Security include children, widows and widowers who've lost working mates, disabled people who can no longer work, and even the former spouses of breadwinners."},
 {'query_id': 150905,
  'query': 'different types of social security disability',
  'label': 0,
  'passage_text': "Maximize Social Security benefit amount based on the various types you may qualify to receive. En español | Q: I'm trying to figure out what Social Security benefits I might qualify for. But it's confusing — there are so many different kinds."},
 {'query_id': 150905,
  'query': 'different types of social security disability',
  'label': 0,
  'passage_text': 'Social Security Disability Insurance pays benefits to you and certain members of your family if you are insured, meaning that you worked long enough and paid Social Security taxes. Supplemental Security Income pays benefits based on financial need.'},
 {'query_id': 150905,
  'query': 'different types of social security disability',
  'label': 0,
  'passage_text': 'Disability Benefit Types and Qualifications. There are several types of disability benefits available depending on an individuals circumstances. The best known are Social Security disability benefits. Social Security Disability (SSD) benefits are available to workers who have paid into the Social Security system through payroll deductions.'},
 {'query_id': 150905,
  'query': 'different types of social security disability',
  'label': 0,
  'passage_text': 'Generally, you need 10 years of work in a job in which you pay Social Security taxes to be eligible for retirement benefits. You can apply for these benefits as early as age 62 or as late as age 70, with the monthly amount going up the longer you put it off.'},
 {'query_id': 150905,
  'query': 'different types of social security disability',
  'label': 1,
  'passage_text': 'There are five major types of Social Security disability benefits. Social Security Disability Insurance Benefits (SSDI) is the most important type of Social Security disability benefits. It goes to individuals who have worked in recent years (five out of the last 10 years in most cases) who are now disabled.'},
 {'query_id': 150905,
  'query': 'different types of social security disability',
  'label': 1,
  'passage_text': 'There are at least five major types of Social Security disability benefits. Disability Insurance Benefits (DIB) is the most important type of Social Security disability benefits. It goes to individuals who have worked in recent years (five out of the last 10 years in most cases) and are now disabled.'},
 {'query_id': 150905,
  'query': 'different types of social security disability',
  'label': 0,
  'passage_text': '← Back to Articles. There are several types of disability benefits available depending on an individuals circumstances. The best known are Social Security disability benefits. Social Security Disability (SSD) benefits are available to workers who have paid into the Social Security system through payroll deductions.'},
 {'query_id': 150905,
  'query': 'different types of social security disability',
  'label': 0,
  'passage_text': 'Benefits for People with Disabilities. The Social Security and Supplemental Security Income disability programs are the largest of several Federal programs that provide assistance to people with disabilities.'},
 {'query_id': 637862,
  'query': 'what does france grow and produce',
  'label': 1,
  'passage_text': 'One-third of France’s land is crop growing. Wheat is the major single crop grown at large farms in the Paris Basin and in the north.In southern France, most of the grapes produced are used in making wine being of high quality that come from several regions.In the Mediterranean region, grapes are used for cheaper wines.heat is the major single crop grown at large farms in the Paris Basin and in the north. In southern France, most of the grapes produced are used in making wine being of high quality that come from several regions.'},
 {'query_id': 637862,
  'query': 'what does france grow and produce',
  'label': 0,
  'passage_text': 'France has been one of the most dominant agricultural centers of Europe for centuries. That gave France an important role in European and, to some extent world, affairs in the pre-industrial age.he major agricultural products that place France among the top producers in the world market are sugar beets, wine, milk, beef and veal, cereals, and oilseeds.'},
 {'query_id': 637862,
  'query': 'what does france grow and produce',
  'label': 1,
  'passage_text': "France is one of the largest wine producers in the world. French wine traces its history to the 6th century BC, with many of France's regions dating their wine-making history to Roman times.The wines produced range from expensive high-end wines sold internationally to more modest wines usually only seen within France.rance is the source of many grape varieties (Cabernet Sauvignon, Chardonnay, Pinot noir, Sauvignon blanc, Syrah) that are now planted throughout the world, as well as wine-making practices and styles of wine that have been adopted in other producing countries."},
 {'query_id': 637862,
  'query': 'what does france grow and produce',
  'label': 0,
  'passage_text': 'The country is the largest agricultural producer in Western Europe and one of the world’s leading exporters of farm products. All the farms have electricity, and most have modern farm machinery with an average holding of 28 hectares. Nearly two-thirds of French farm income comes from meat and dairy animals.heat is the major single crop grown at large farms in the Paris Basin and in the north. In southern France, most of the grapes produced are used in making wine being of high quality that come from several regions.'},
 {'query_id': 637862,
  'query': 'what does france grow and produce',
  'label': 0,
  'passage_text': 'Food of France-a regional guide. You are here: French recipes French foods by region. When people talk of French food in restaurants they are usually referring to sophistication, fine food and wine and expensive restaurants.outh-West France: In the south-west of France the emphasis is on rich foods. The main specialities are duck, foie gras, prunes, oysters, mushrooms and truffles. And of course a nice rich red Bordeaux wine to go with it.'},
 {'query_id': 637862,
  'query': 'what does france grow and produce',
  'label': 0,
  'passage_text': "The most important crop was wheat. Wheat was used to make flour. The farmers ground the wheat grains in the seigneur's flour mill. They would pay the seigneur with part of the … flour for the use of his mill. France may be a small country in Western Europe, but the impact of French cu…. 2  The Weather in France Though France is only the size of Texas, it is situated in an area where weather varies greatly."},
 {'query_id': 637862,
  'query': 'what does france grow and produce',
  'label': 0,
  'passage_text': 'Confidence votes 902. Various plants such as cereals, wheat, barely, oat, corn are grown in France. Crops such as grapes, corn, barely rapeseed are also cultivated.onfidence votes 902. Various plants such as cereals, wheat, barely, oat, corn are grown in France. Crops such as grapes, corn, barely rapeseed are also cultivated.'},
 {'query_id': 637862,
  'query': 'what does france grow and produce',
  'label': 0,
  'passage_text': "France's forests have grown 35 percent since 1945 and continue to grow by about 30,000 hectares each year. Close to 4 million people in France have private ownership of wooded areas. The marketed wood harvest was up in 1998 from its level in 1997 by about 1.6 percent.he major agricultural products that place France among the top producers in the world market are sugar beets, wine, milk, beef and veal, cereals, and oilseeds."},
 {'query_id': 637862,
  'query': 'what does france grow and produce',
  'label': 0,
  'passage_text': 'It takes second place in both the EU and the world in the production of its highly popular wine varieties, with 5.3 million metric tons. Though fifth in the world, France ranks second in the EU in milk production, totaling 23.3 million metric tons.he major agricultural products that place France among the top producers in the world market are sugar beets, wine, milk, beef and veal, cereals, and oilseeds.'},
 {'query_id': 637862,
  'query': 'what does france grow and produce',
  'label': 0,
  'passage_text': 'Ironic really, because the average French person can (and does) eat well in a restaurant less expensively than his counterparts in many other countries. The difference lies rather in the knowledge of local French food, and interest in food, of the average French person compared with most other countries.outh-West France: In the south-west of France the emphasis is on rich foods. The main specialities are duck, foie gras, prunes, oysters, mushrooms and truffles. And of course a nice rich red Bordeaux wine to go with it.'}]

In [155]:
def create_df(row):
    
    if(len(row['passages'])!=10):
        return
    zero_passage_text =''
    
    for dicto2 in row['passages']:
        if(dicto2['is_selected']==0):
            zero_passage_text = dicto2['passage_text']
            break;
    i = 0 
    is_1_found = False
    for dicto1 in row['passages']:
        dicto = {}
        dicto['query_id'] = row['query_id'] 
        dicto['query'] = row['query']
        is_selected = dicto1['is_selected']
        if(is_selected ==1):
            if(is_1_found):
                dicto['label'] = 0
                dicto['passage_text'] = zero_passage_text
            else:
                dicto['label'] = dicto1['is_selected']
                dicto['passage_text'] = dicto1['passage_text']
            is_1_found =True
        else:
            dicto['label'] = dicto1['is_selected']
            dicto['passage_text'] = dicto1['passage_text']
        dicto['passage_id'] = i
        i+=1
        rows.append(dicto)

In [67]:
df_combined

,answers,passages,query,query_id,query_type,wellFormedAnswers
0,['The immediate impact of the success of the m...,"[{'is_selected': 1, 'passage_text': 'The prese...",)what was the immediate impact of the success ...,1185869,DESCRIPTION,[]
1,['Restorative justice that fosters dialogue be...,"[{'is_selected': 0, 'passage_text': 'group dis...",_________ justice is designed to repair the ha...,1185868,DESCRIPTION,[]
10,['The reasons why Stalin wanted to control Eas...,"[{'is_selected': 0, 'passage_text': 'Western b...",why did stalin want control of eastern europe,1185854,DESCRIPTION,[]
100,['Nails rust in water because water allows the...,"[{'is_selected': 0, 'passage_text': 'what to D...",why do nails get rusty,1185755,DESCRIPTION,[]
1000,"['Depona Ab is a library in Vilhelmina, Sweden.']","[{'is_selected': 0, 'passage_text': 'A preview...",depona ab,1184773,DESCRIPTION,[]

In [44]:
df_y.shape[0]

55636

In [19]:
list = list(test['query_id'].unique())

,query_id,query,passage_text,passage_id
0,1135787,distance between erie in buffalo new york,Erie Canal Distance Tables The Erie Canal is t...,0
1,1135787,distance between erie in buffalo new york,What is the distance between Erie AND Buffalo?...,1
2,1135787,distance between erie in buffalo new york,The distance between Erie and Buffalo in a str...,2
3,1135787,distance between erie in buffalo new york,Erie Canal Distances. Erie Canal Distance Tabl...,3
4,1135787,distance between erie in buffalo new york,Erie's Metropolitan Area consists of approxima...,4
5,1135787,distance between erie in buffalo new york,This will help you estimate how much time you ...,5
6,1135787,distance between erie in buffalo new york,"As a general guide, Albany to Oswego, NY will ...",6
7,1135787,distance between erie in buffalo new york,"Erie, PA. {{::location.tagLine.value.text}}. C...",7
8,1135787,distance between erie in buffalo new york,"You start your flight Distance from Buffalo, N...",8
9,1135787,distance between erie in buffalo new york,What is the distance between Erie AND Buffalo?...,9
10,281922,how many days would it take to get to pluto,The asteroid belt is nothing but tourist traps...,0
11,281922,how many days would it take to get to pluto,(Except we'll never get them back to plug into...,1
12,281922,how many days would it take to get to pluto,"At the Shuttle's maximum speed of about 30,000...",2
13,281922,how many days would it take to get to pluto,That means we will spend the next 16 months tr...,3
14,281922,how many days would it take to get to pluto,It takes about four hours and 25 minutes for a...,4
15,281922,how many days would it take to get to pluto,On the Space Shuttle. The distance from Earth ...,5
16,281922,how many days would it take to get to pluto,"This week, as a box of electronics called New ...",6
17,281922,how many days would it take to get to pluto,So if you know the exact distance between Eart...,7
18,281922,how many days would it take to get to pluto,It comes as close to the sun as 30 or so AU (i...,8
19,281922,how many days would it take to get to pluto,"So, when New Horizons zooms past Pluto on July...",9
20,120233,define dew point.,Dew Point Temperature (Td). Is the expected de...,0
21,120233,define dew point.,While relative humidity is (as its name sugges...,1
22,120233,define dew point.,dew point. English Collins Dictionary-English ...,2
23,120233,define dew point.,The dewpoint temperature is the temperature at...,3
24,120233,define dew point.,English Collins Dictionary-English synonyms & ...,4
25,120233,define dew point.,The dew point is the temperature to which the ...,5
26,120233,define dew point.,"If there is then further cooling of the air, s...",6
27,120233,define dew point.,dew point. [dyo̅o̅]. the temperature at which ...,7
28,120233,define dew point.,dew point the temperature at which moisture in...,8
29,120233,define dew point.,The dew point is always lower than (or equal t...,9
...,...,...,...,...
104140,138632,definition of tangent,Abbr. tan The trigonometric function of an acu...,0
104141,138632,definition of tangent,A tangent is an entirely different topic or di...,1
104142,138632,definition of tangent,tangent - a straight line or plane that touche...,2
104143,138632,definition of tangent,more ... A line that just touches a curve at o...,3
104144,138632,definition of tangent,"4. (Music, other) music a part of the action o...",4
104145,138632,definition of tangent,Trigonometric functions are commonly defined a...,5
104146,138632,definition of tangent,"In mathematics, the trigonometric functions (a...",6
104147,138632,definition of tangent,1. a line or plane that touches but does not i...,7
104148,138632,definition of tangent,"The sine, tangent, and secant functions of an ...",8
104149,138632,definition of tangent,n a straight line or plane that touches a curv...,9
104150,50782,benefits of fermented ginger tea,For the Ginger Bug: Mix 2 tablespoons grated g...,0
104151,50782,benefits of fermented ginger tea,Instructions. 1 For the Ginger Bug: Mix 2 tab...,1
104152,50782,benefits of fermented ginger tea,Daily Natural Remedies Natural Lifestyle Tips....,2
104153,50782,benefits of fermented ginger tea,Benefits of Fermented Tea with Ginger and Turm...,3
104154,50782,benefits of fermented ginger tea,Learn how to make (almost sugar-free) fermente...,4
104155,50782,benefits of fermented ginger tea,Because ginger is so concentrated with gingero...,5
104156,50782,benefits of fermented ginger tea,Here are just a few benefits of fermented food...,6
104157,50782,benefits of fermented ginger tea,Benefits of Fermented Tea with Ginger and Turm...,7
104158,50782,benefits of fermented ginger tea,Benefits of Fermented Tea with Ginger and Turm...,8
104159,50782,benefits of fermented ginger tea,There’s so much to this tea that people don’t ...,9
104160,83375,cast of godspell at ad players,Find out what's currently playing and what's c...,0
104161,83375,cast of godspell at ad players,The cast of Godspell includes A. D. Players' r...,1
104162,83375,cast of godspell at ad players,"Godspell is a musical, composed by Stephen Sch...",2
104163,83375,cast of godspell at ad players,"Godspell also features the international hit, ...",3
104164,83375,cast of godspell at ad players,"A. D. Players' Grace Theater, 2710 W. Alabama,...",4
104165,83375,cast of godspell at ad players,A professional theater ministry communicating ...,5
104166,83375,cast of godspell at ad players,Staples Players shows are seen by more than 15...,6
104167,83375,cast of godspell at ad players,A. D. Players announces that Godspell will ope...,7
104168,83375,cast of godspell at ad players,"Based on the Gospel according to Matthew, Gods...",8
104169,83375,cast of godspell at ad players,Our Sponsors. › 1 visit site. › 2 visit site...,9

In [47]:
sorted_train_data = pd.read_csv('../data/sorted_train.csv')

In [50]:
sorted_train_data.shape[0]/10

524188.0

In [56]:
sorted_train_data['passage_text'] = sorted_train_data['passage_text'].astype('str')

In [60]:
sorted_train_data[sorted_train_data['query'].str.contains("why did stalin want control of eastern europe")]

,query_id,query,passage_text,label,passage_id
5167190,516720,why did stalin want control of eastern europe,Western betrayal. The concept of Western betra...,0,0
5167191,516720,why did stalin want control of eastern europe,"The Tuvan People's Republic, was proclaimed in...",0,1
5167192,516720,why did stalin want control of eastern europe,Satellite state. The term satellite state desi...,0,2
5167193,516720,why did stalin want control of eastern europe,"According to Hakluyt, why should England pursu...",0,3
5167194,516720,why did stalin want control of eastern europe,An interview with Anne Applebaum about her new...,0,4
5167195,516720,why did stalin want control of eastern europe,"They therefore,if anything, tightened their gr...",0,5
5167196,516720,why did stalin want control of eastern europe,There are 3 main reasons why Stalin wanted to ...,1,6
5167197,516720,why did stalin want control of eastern europe,Why did the United Nations send troops to Kore...,0,7
5167198,516720,why did stalin want control of eastern europe,"On top of that, Russia had been the victim of ...",0,8
5167199,516720,why did stalin want control of eastern europe,"Not just Eastern Europe, Stalin wanted to cont...",0,9

In [54]:
df_x[~df_x['query_id'].isin(list(sorted_train_data['query_id'].unique()))]

,answers,passages,query,query_id,query_type,wellFormedAnswers
0,['The immediate impact of the success of the m...,"[{'is_selected': 1, 'passage_text': 'The prese...",)what was the immediate impact of the success ...,1185869,DESCRIPTION,[]
1,['Restorative justice that fosters dialogue be...,"[{'is_selected': 0, 'passage_text': 'group dis...",_________ justice is designed to repair the ha...,1185868,DESCRIPTION,[]
10,['The reasons why Stalin wanted to control Eas...,"[{'is_selected': 0, 'passage_text': 'Western b...",why did stalin want control of eastern europe,1185854,DESCRIPTION,[]
100,['Nails rust in water because water allows the...,"[{'is_selected': 0, 'passage_text': 'what to D...",why do nails get rusty,1185755,DESCRIPTION,[]
1000,"['Depona Ab is a library in Vilhelmina, Sweden.']","[{'is_selected': 0, 'passage_text': 'A preview...",depona ab,1184773,DESCRIPTION,[]
100005,"['An abbreviation of Conformite Conformité, eu...","[{'is_selected': 0, 'passage_text': 'CE Certif...",what is ce certified,728808,DESCRIPTION,[]
10001,['The customer support phone number of BancFir...,"[{'is_selected': 0, 'passage_text': 'Oklahoma ...",bancfirst customer service number,1174761,NUMERIC,[]
100011,"['DeWitt is located in Clinton County, Michiga...","[{'is_selected': 0, 'passage_text': 'DeWitt wa...",what county is dewitt michigan in?,605123,LOCATION,[]
100013,"[""A motorized oxygen mask doesn't qualify to m...","[{'is_selected': 1, 'passage_text': 'It might ...",using cpap without prescription,534802,DESCRIPTION,[]
100014,"[""It allows passengers to check-in to a flight...","[{'is_selected': 0, 'passage_text': 'A confirm...",what is early bird check in southwest,742216,ENTITY,[]
100016,['Bartholomew'],"[{'is_selected': 0, 'passage_text': 'WELCOME T...",what county is columbus city in,604568,LOCATION,[Columbus is a city in Bartholomew County.]
100019,"['Shelton is in Fairfield County, Connecticut,...","[{'is_selected': 0, 'passage_text': 'My husban...","what county is shelton, ct",612660,LOCATION,[]
10002,"['Yes, the bachelor is legal.']","[{'is_selected': 0, 'passage_text': 'Arconic’s...",is the bachelor legal,1174759,DESCRIPTION,[]
100020,"['Average $111,082,']","[{'is_selected': 1, 'passage_text': 'Bp Americ...",what is BP level j salary,672511,NUMERIC,[]
100022,"[""DBA means 'Doing business as' is a term that...","[{'is_selected': 0, 'passage_text': 'In this p...",what dba mean,617187,DESCRIPTION,[]
100025,['Chronic Obstructive Pulmonary Disease and So...,"[{'is_selected': 0, 'passage_text': 'Disabilit...",what disability is copd,620911,DESCRIPTION,[]
100027,['A contemporary Asian dish consisting of an o...,"[{'is_selected': 0, 'passage_text': 'In one co...",what is a omurice omelet,693333,DESCRIPTION,[An omurice omelet is a contemporary Asian dis...
100031,['Crucial for proper brain function and plays ...,"[{'is_selected': 0, 'passage_text': 'Folate an...",what does folic acid do,637779,DESCRIPTION,[Folic acid is crucial for proper brain functi...
100033,['Pinellas County'],"[{'is_selected': 0, 'passage_text': '1 To chan...",what county is seminole fl in,612569,LOCATION,"[Seminole, Florida is in Pinellas County.]"
100035,['Yes'],"[{'is_selected': 1, 'passage_text': 'Big Bus T...",tripadvisor does the london hop on off bus pri...,524802,NUMERIC,[]
100036,['A ring of small red or skin-coloured bumps'],"[{'is_selected': 0, 'passage_text': 'Granuloma...",what does granuloma annulare look like,638438,DESCRIPTION,[]
100040,['Onondaga'],"[{'is_selected': 0, 'passage_text': 'These tra...",what county is nine mile in,610348,LOCATION,[Nine Mile is in Onondaga county.]
100041,['Salpingectomy is the surgical removal of one...,"[{'is_selected': 0, 'passage_text': 'SGO Clini...",what is a salpingectomies,698805,DESCRIPTION,[Salpingectomy is the surgical removal of one ...
100044,['A triglyceride is an ester derived from glyc...,"[{'is_selected': 1, 'passage_text': 'A triglyc...",triglycerides what are they,524762,DESCRIPTION,[]
100047,"['Trauma, Periodontitis, Orthodontic treatment...","[{'is_selected': 1, 'passage_text': 'What caus...",what causes resorption of teeth,591215,DESCRIPTION,"[Trauma, periodontitis, orthodontic treatment,..."
10005,"['Yes, Cheetah is considered Endangered specie...","[{'is_selected': 0, 'passage_text': 'Cheetahs ...",is the cheetah an endangered species,1174756,ENTITY,[]
100052,['It include garcinia cambogia (a former scien...,"[{'is_selected': 0, 'passage_text': 'Garcinia ...",what is in garcinia cambogia,758101,DESCRIPTION,[]
10006,"['Yes,the Cobb house haunted in Vicksburg Miss...","[{'is_selected': 0, 'passage_text': 'Haunted T...",is the cobb house haunted in vicksburg mississ...,1174755,DESCRIPTION,[]
100061,['1 Partnership name. 2 Business address. 3 Na...,"[{'is_selected': 0, 'passage_text': 'You'll wa...",what do you put at purpose for partnership agr...,626917,DESCRIPTION,[]
100068,['Phish is try to obtain financial or other co...,"[{'is_selected': 0, 'passage_text': 'Commentin...",what are phish,563205,DESCRIPTION,[]
...,...,...,...,...,...,...
99908,['It is genus of Coccus (spherical).'],"[{'is_selected': 1, 'passage_text': 'Streptoco...",what cell morphology does streptococcus saprop...,594075,DESCRIPTION,[]
99909,"['Smoke, sulphur dioxide and other components.']","[{'is_selected': 0, 'passage_text': 'Smog, for...",what are the major components of smog,571338,DESCRIPTION,"[The major components of smog are smoke, sulph..."
9991,['Coconut oil is better for lice.'],"[{'is_selected': 0, 'passage_text': 'Lice disl...",is tea tree oil or coconut oil better for lice,1174772,DESCRIPTION,[]
99911,['An act of kindness from a big nonprofit to a...,"[{'is_selected': 0, 'passage_text': 'Fiscal ag...",what is a fiscal agent sponsor,683334,DESCRIPTION,[The fiscal agent sponsor is an act of kindnes...
99918,['An indicator that orients you generally; it ...,"[{'is_selected': 0, 'passage_text': 'According...",what is a reference point in science,697650,DESCRIPTION,[A reference point is an indicator that orient...
9992,['Achievement is the act of achieving or perfo...,"[{'is_selected': 0, 'passage_text': 'We should...",achievement define,1174771,DESCRIPTION,[]
99925,"[""Dormancy is a period in an organism's life c...","[{'is_selected': 1, 'passage_text': 'Dormancy ...",what dormancy means,655694,DESCRIPTION,[Dormancy is a period in an organism's life cy...
99927,['Memories of significant personal events and ...,"[{'is_selected': 0, 'passage_text': 'Autobiogr...",what is autobiographical memory,721104,DESCRIPTION,[]
99939,"['Class A, B, C, D, E.']","[{'is_selected': 1, 'passage_text': '1 The num...",what category is an electrical fire,583571,DESCRIPTION,[]
99940,['1 Giant cell arteritis. 2 Migraine. 3 Tensio...,"[{'is_selected': 0, 'passage_text': 'Scalp ten...",what can cause scalp soreness,581452,DESCRIPTION,[]
99941,['Helicases'],"[{'is_selected': 0, 'passage_text': 'In bacter...",what enzyme causes dna to unzip,657490,DESCRIPTION,[Helicases enzyme causes DNA to unzip.]
9995,['The Eastern part of Texas is in the Central ...,"[{'is_selected': 0, 'passage_text': 'Central T...",is texas central time or eastern time,1174767,DESCRIPTION,[]
99952,['A county island is an area of unincorporated...,"[{'is_selected': 1, 'passage_text': 'A county ...",what is an unincorporated island in a city,717553,LOCATION,[A county island is an area of unincorporated ...
99954,['Applied to a machine every time the operatin...,"[{'is_selected': 0, 'passage_text': 'Group Pol...",what group policies are applied,664606,DESCRIPTION,[Group policies are applied to a machine every...
99959,['An explicit formula is a formula we can use ...,"[{'is_selected': 0, 'passage_text': 'explicit ...",what does explicit formula mean,637272,DESCRIPTION,[]
99963,['Completely Automated Public Turing Test to T...,"[{'is_selected': 0, 'passage_text': 'Freebase(...",what does the acronym captcha stand for,649330,DESCRIPTION,[The acronym CAPTCHA stands for Completely Aut...
99966,"['Rodents, fish, crustaceans, amphibians, and ...","[{'is_selected': 0, 'passage_text': 'Mink trac...",what do mink eat,623976,ENTITY,"[Mink eats rodents, fish, crustaceans, amphibi..."
99968,['Feel worthless and hopeless'],"[{'is_selected': 0, 'passage_text': 'Do one bi...",what happens when someone heart is broken,667354,DESCRIPTION,[]
9997,"['Yes, Charles Bronson is dead.']","[{'is_selected': 0, 'passage_text': 'After mov...",is the actor charles bronson dead,1174765,PERSON,[]
99972,['Yes'],"[{'is_selected': 0, 'passage_text': 'He was th...",was william henry harrison a republican,541259,DESCRIPTION,[]
99973,"['Fairbury is in Livingston County, Illinois.']","[{'is_selected': 1, 'passage_text': '407 Walnu...",what county is fairbury il,605770,LOCATION,[]
99977,"['11 pounds', '22-50 pounds']","[{'is_selected': 0, 'passage_text': 'Rated 4 o...",weight evenflo maestro,547249,NUMERIC,[The weight of Evenflo Maestro is 11 pounds.]
9998,"['Yes, iPad Pro is water resistant.']","[{'is_selected': 0, 'passage_text': 'Apple's n...",is the apple ipad water resistant?,1174764,DESCRIPTION,[]
99986,['A floating museum is in New York City.'],"[{'is_selected': 1, 'passage_text': 'Intrepid ...",what city is a floating museum,595815,LOCATION,[]
99988,"['Carbon dioxide, methane and other greenhouse...","[{'is_selected': 1, 'passage_text': 'Global wa...",what causes the greenhouse effect,592625,DESCRIPTION,[]
9999,"['Yes, the asthenosphere made of iron and nick...","[{'is_selected': 1, 'passage_text': 'The asthe...",is the asthenosphere made of iron and nickel,1174763,DESCRIPTION,[]
99992,"['WBC is 5 to 10 K/uL, HGB is 12 to 17.4 g/dL.']","[{'is_selected': 0, 'passage_text': 'A complet...",what is human blood value on a cbc,756122,DESCRIPTION,[]
99993,['Used to treat inflammation of small areas of...,"[{'is_selected': 0, 'passage_text': 'What is c...",what is a cortisone injection used for,679433,DESCRIPTION,[A cortisone injection is used to treat inflam...
99996,['Galveston County'],"[{'is_selected': 0, 'passage_text': 'Most of t...",what county is hitchcock texas located in,607295,LOCATION,[]
99997,['All about great blowout style for about thir...,"[{'is_selected': 0, 'passage_text': 'And with ...",what is blowout for hair,724819,DESCRIPTION,[]

In [53]:
df_y[df_y['query_id'].isin(list(sorted_train_data['query_id'].unique()))]

,answers,passages,query,query_id,query_type,wellFormedAnswers
100000,"['Globally 8,640,000 lightning strikes per day.']","[{'is_selected': 0, 'passage_text': 'Lightning...",average number of lightning strikes per day,39449,NUMERIC,[]
100001,"['Yes, over fertilizing can burn lawn.']","[{'is_selected': 0, 'passage_text': 'Verify th...",can you burn your lawn with fertilizer,76162,DESCRIPTION,[]
100007,['The meaning of the name Goch is red.'],"[{'is_selected': 0, 'passage_text': 'See the G...",goch meaning,195512,DESCRIPTION,[]
100010,['For anxiety treatment is 1 mg two to three t...,"[{'is_selected': 0, 'passage_text': 'Pdoc gave...",how often can ativan be taken,331318,NUMERIC,[]
100012,['William Bradford served thirty years as Gove...,"[{'is_selected': 0, 'passage_text': 'Added 201...",how many years did william bradford serve as g...,300674,NUMERIC,[]
100013,"['2,662']","[{'is_selected': 0, 'passage_text': 'City of A...",albany mn population,15177,NUMERIC,"[The population of Albany, Minnesota is 2,662. ]"
100015,"['It means preventing, hindering, or acting as...","[{'is_selected': 1, 'passage_text': 'Adjective...",define preventive,125705,DESCRIPTION,[]
100017,"['An infection, heredity or an abnormality of ...","[{'is_selected': 0, 'passage_text': 'Achalasia...",causes of achalasia,85224,DESCRIPTION,[]
100019,['The Volcano forecast for Apr 12 is 52 degree...,"[{'is_selected': 1, 'passage_text': 'Volcano 1...","current weather in volcano, ca",114414,DESCRIPTION,[The Volcano forecast for Apr 12 is 52 degrees...
100024,['6 to 10 days'],"[{'is_selected': 0, 'passage_text': 'Symptoms ...",how many days after ovulation can i tell i'm p...,280709,NUMERIC,[]
100026,['The cost of a first-class postage stamp is n...,"[{'is_selected': 0, 'passage_text': 'The idea ...",how much are postage stamps right now,302299,NUMERIC,[]
100028,['A great way to add a touch of color without ...,"[{'is_selected': 0, 'passage_text': 'Changing ...",color overlay photoshop,94798,DESCRIPTION,[]
100031,['It has a mild humid temperate climate with w...,"[{'is_selected': 0, 'passage_text': 'The clima...",average temperature cardiff wales,44932,NUMERIC,[]
100036,['The highest paying subspecialty in orthopedi...,"[{'is_selected': 0, 'passage_text': 'This sala...",highest paying subspecialty in orthopedics,202671,ENTITY,[]
100037,['Hippocrates'],"[{'is_selected': 0, 'passage_text': 'Hippocrat...",____________________ is considered the father ...,9083,DESCRIPTION,[Hippocrates is considered the father of moder...
100044,['Yes'],"[{'is_selected': 0, 'passage_text': 'How long ...",does xpress bet charge to deposit money in you...,174249,DESCRIPTION,[]
100047,['The distance from Faribault to Winona is 95M...,"[{'is_selected': 0, 'passage_text': 'Winona, M...",how far is faribault from winona?,230982,NUMERIC,[]
100048,['120 days from the date of the Note.'],"[{'is_selected': 0, 'passage_text': 'New and U...",how many days is an appraisal good for a fanni...,281439,NUMERIC,[An appraisal is good for 120 days from the da...
100049,['The CRM/Outlook synchronization process can ...,"[{'is_selected': 0, 'passage_text': 'Dynamics ...",dynamics crm outlook synchronization process,177008,DESCRIPTION,[]
100050,['Wisdom teeth recovery time is three to four ...,"[{'is_selected': 1, 'passage_text': 'You shoul...",how long to recover from wisdom teeth removal,271872,NUMERIC,[]
100051,"['From $26,000 to $39,000 a year']","[{'is_selected': 0, 'passage_text': 'If you ar...",average pharmacy tech salary,40287,NUMERIC,[The average salary for a pharmacy technician ...
100052,['1 Skin care: For a clearer complexion and to...,"[{'is_selected': 1, 'passage_text': 'Major Ben...",benefits of lymphatic drainage facial,50983,DESCRIPTION,[]
100061,"[""Half of the country's Spanish-speakers resid...","[{'is_selected': 0, 'passage_text': 'Spanish l...",english is the official state language in some...,180613,ENTITY,[]
100062,['The forms are valid for 30 days after issuan...,"[{'is_selected': 0, 'passage_text': 'Chapter 9...",how long is a voe valid,263012,NUMERIC,[]
100065,['3.7 grams carbohydrate in asparagus.'],"[{'is_selected': 0, 'passage_text': 'There are...",how many carbohydrates in asparagus,278291,NUMERIC,[]
100069,['DRAM (Dynamic Random Access Memory) and SODI...,"[{'is_selected': 0, 'passage_text': 'Flash mem...",different types of memory of a computer,150649,DESCRIPTION,[]
100070,['80 calories'],"[{'is_selected': 0, 'passage_text': 'Calories ...",how many calories in average apple,277271,NUMERIC,"[An average apple has 80 calories., There are ..."
100071,"['$110,000 to $130,000 per year.']","[{'is_selected': 0, 'passage_text': 'Marketing...",how much would graduate marketers make?,330883,NUMERIC,[]
100073,"[""Yes, While you can set Chrome as a default b...","[{'is_selected': 1, 'passage_text': 'While you...",can you set google chrome as your default web ...,79604,DESCRIPTION,[]
100075,['340 calories in a 1 burger serving out of wh...,"[{'is_selected': 0, 'passage_text': 'There are...",how much fat is in a bubba burger,319445,NUMERIC,[]
...,...,...,...,...,...,...
99930,"['Yes, coconut oil treats yeast.']","[{'is_selected': 1, 'passage_text': 'To use co...",does coconut oil treat yeast,164814,DESCRIPTION,[]
99932,['4'],"[{'is_selected': 0, 'passage_text': 'How many ...",how many grams of sugar in one sugar packet,285214,NUMERIC,[There are 4 grams of sugar in one sugar packet.]
99933,['4 bp.'],"[{'is_selected': 0, 'passage_text': 'Men's Hea...",average size of an enzyme,43997,NUMERIC,[]
99934,['7 home games and 5 away games in the regular...,"[{'is_selected': 1, 'passage_text': 'Mississip...",2015 mississippi state football schedule,1021,LOCATION,"[In 2015, the schedule of the Mississippi Stat..."
99935,['The act or an instance of entering.'],"[{'is_selected': 0, 'passage_text': 'Blog. A m...",definition entranced,130641,DESCRIPTION,[]
99936,['$48.00'],"[{'is_selected': 1, 'passage_text': '1 A heart...",how much does it cost for dog to be tested for...,314458,NUMERIC,[The cost for dog to be tested for heartworms ...
99939,"['$52,000']","[{'is_selected': 1, 'passage_text': 'The avera...",average salary for college grad,42212,NUMERIC,[The average salary for a college graduate is ...
99941,['Moisture should penetrate to about 6 to 8 in...,"[{'is_selected': 0, 'passage_text': 'Knowing h...",how to properly water your grass,373938,DESCRIPTION,[]
99944,['A membrane-bound compartment or structure in...,"[{'is_selected': 0, 'passage_text': 'However, ...",cell organelles definition,89573,DESCRIPTION,[Cell organelles is a membrane bound compartme...
99946,"['Yes, bactrim work to treat diverticulitis.']","[{'is_selected': 0, 'passage_text': 'If the pa...",does bactrim work to treat diverticulitis,163622,DESCRIPTION,[]
99948,"['Yes,Rosacea is a facial skin condition that ...","[{'is_selected': 0, 'passage_text': 'By Mayo C...",does adult acne rosacea give you blepharitis,162662,DESCRIPTION,[]
99949,['Yes'],"[{'is_selected': 0, 'passage_text': 'It turns ...",do gemstones have thermal properties,156436,DESCRIPTION,[]
99953,['One-thousanth'],"[{'is_selected': 0, 'passage_text': '1 To conv...",how many milliliters are in a meter?,289301,NUMERIC,[There are one thousand milliliters in a meter.]
99954,"['Mastication, taste, deglutition, articulatio...","[{'is_selected': 0, 'passage_text': 'Tongue an...",function of tongue,192540,DESCRIPTION,"[The function of the tongue is mastication, ta..."
99960,['Generally 10 months'],"[{'is_selected': 0, 'passage_text': 'Homepage ...",how many months in a university academic year,289922,NUMERIC,[There are generally 10 months in a university...
99963,['One millimeter of length converted to micron...,"[{'is_selected': 0, 'passage_text': 'Convertin...",convert microns to millimeters,98729,NUMERIC,[One millimeter of length converted to micron ...
99967,['It refers to electronic harassment or bullyi...,"[{'is_selected': 1, 'passage_text': 'Cyberbull...",cyber harassment definition,114698,DESCRIPTION,[]
99969,['Ginger has long been used in Asia to treat m...,"[{'is_selected': 0, 'passage_text': 'Cesar’s A...",how to keep a dog from getting motion sickness,366060,DESCRIPTION,[]
99975,['About 12 minutes.'],"[{'is_selected': 0, 'passage_text': '{{model.a...",how long do you cook a hard boiled egg,247441,NUMERIC,[]
99977,['It is recommended that you take a practice n...,"[{'is_selected': 1, 'passage_text': 'Oklahoma ...",how to become a notary oklahoma,345237,DESCRIPTION,[It is recommended that you take a practice no...
99982,['25-26 minutes.'],"[{'is_selected': 0, 'passage_text': '1 Top wit...",how long do you bake muffins,247194,NUMERIC,[]
99985,['$2 to $5 per square foot.'],"[{'is_selected': 0, 'passage_text': 'Vinyl, ac...",cost per foot on hardy plank installation,108172,NUMERIC,[]
99986,['$ 50 to $ 200'],"[{'is_selected': 1, 'passage_text': 'according...",how much does a pap smear cost,310713,NUMERIC,[]
99987,['1 to 2 days.'],"[{'is_selected': 0, 'passage_text': 'When I wa...",how long does it take to mail a card usps,257688,NUMERIC,[]
99988,['The meaning of glioma is a tumor springing f...,"[{'is_selected': 0, 'passage_text': 'Optic Gli...",glioma meaning,195199,DESCRIPTION,[]
99990,"['Pizza, pasta and ice cream.']","[{'is_selected': 0, 'passage_text': 'Kashmiri ...",different types of cuisines,150337,DESCRIPTION,[]
99992,"['Yes, electric cleansers are safe.']","[{'is_selected': 0, 'passage_text': 'Features ...",are electric cleansers safe?,22241,DESCRIPTION,[]
99995,"['It is defined as the quality of being wide, ...","[{'is_selected': 0, 'passage_text': '1 The sta...",define width,129177,NUMERIC,[]
99996,['Human Resource Management is the term used t...,"[{'is_selected': 1, 'passage_text': 'Human Res...",forbes definition of human resource management,190655,DESCRIPTION,[]
99999,['List the elements you want to include in a h...,"[{'is_selected': 0, 'passage_text': 'Business ...",how to offer health insurance to employees,371455,DESCRIPTION,[]

In [14]:
df_eval_y

,answers,passages,query,query_id,query_type,wellFormedAnswers
0,['A corporation is a company or group of peopl...,"[{'is_selected': 0, 'passage_text': 'A company...",. what is a corporation?,1102432,DESCRIPTION,[]
1,['Rachel Carson writes The Obligation to Endur...,"[{'is_selected': 0, 'passage_text': 'Read to w...",why did rachel carson write an obligation to e...,1102431,DESCRIPTION,[]
10000,['The symptoms of a dying mouse are runny eyes...,"[{'is_selected': 0, 'passage_text': 'This can ...",symptoms of a dying mouse,1090282,ENTITY,[]
100000,"['Globally 8,640,000 lightning strikes per day.']","[{'is_selected': 0, 'passage_text': 'Lightning...",average number of lightning strikes per day,39449,NUMERIC,[]
100001,"['Yes, over fertilizing can burn lawn.']","[{'is_selected': 0, 'passage_text': 'Verify th...",can you burn your lawn with fertilizer,76162,DESCRIPTION,[]
100007,['The meaning of the name Goch is red.'],"[{'is_selected': 0, 'passage_text': 'See the G...",goch meaning,195512,DESCRIPTION,[]
10001,['acidic and extremely painful is symptom of a...,"[{'is_selected': 0, 'passage_text': 'Pain from...",symptoms of a gastric ulcer in women,1090280,ENTITY,[]
100010,['For anxiety treatment is 1 mg two to three t...,"[{'is_selected': 0, 'passage_text': 'Pdoc gave...",how often can ativan be taken,331318,NUMERIC,[]
100012,['William Bradford served thirty years as Gove...,"[{'is_selected': 0, 'passage_text': 'Added 201...",how many years did william bradford serve as g...,300674,NUMERIC,[]
100013,"['2,662']","[{'is_selected': 0, 'passage_text': 'City of A...",albany mn population,15177,NUMERIC,"[The population of Albany, Minnesota is 2,662. ]"
100015,"['It means preventing, hindering, or acting as...","[{'is_selected': 1, 'passage_text': 'Adjective...",define preventive,125705,DESCRIPTION,[]
100017,"['An infection, heredity or an abnormality of ...","[{'is_selected': 0, 'passage_text': 'Achalasia...",causes of achalasia,85224,DESCRIPTION,[]
100019,['The Volcano forecast for Apr 12 is 52 degree...,"[{'is_selected': 1, 'passage_text': 'Volcano 1...","current weather in volcano, ca",114414,DESCRIPTION,[The Volcano forecast for Apr 12 is 52 degrees...
100024,['6 to 10 days'],"[{'is_selected': 0, 'passage_text': 'Symptoms ...",how many days after ovulation can i tell i'm p...,280709,NUMERIC,[]
100026,['The cost of a first-class postage stamp is n...,"[{'is_selected': 0, 'passage_text': 'The idea ...",how much are postage stamps right now,302299,NUMERIC,[]
100028,['A great way to add a touch of color without ...,"[{'is_selected': 0, 'passage_text': 'Changing ...",color overlay photoshop,94798,DESCRIPTION,[]
10003,['High air pollution levels can cause immediat...,"[{'is_selected': 0, 'passage_text': 'Long-term...",symptoms of air pollution exposure,1090278,ENTITY,[]
100031,['It has a mild humid temperate climate with w...,"[{'is_selected': 0, 'passage_text': 'The clima...",average temperature cardiff wales,44932,NUMERIC,[]
100036,['The highest paying subspecialty in orthopedi...,"[{'is_selected': 0, 'passage_text': 'This sala...",highest paying subspecialty in orthopedics,202671,ENTITY,[]
100037,['Hippocrates'],"[{'is_selected': 0, 'passage_text': 'Hippocrat...",____________________ is considered the father ...,9083,DESCRIPTION,[Hippocrates is considered the father of moder...
100044,['Yes'],"[{'is_selected': 0, 'passage_text': 'How long ...",does xpress bet charge to deposit money in you...,174249,DESCRIPTION,[]
100047,['The distance from Faribault to Winona is 95M...,"[{'is_selected': 0, 'passage_text': 'Winona, M...",how far is faribault from winona?,230982,NUMERIC,[]
100048,['120 days from the date of the Note.'],"[{'is_selected': 0, 'passage_text': 'New and U...",how many days is an appraisal good for a fanni...,281439,NUMERIC,[An appraisal is good for 120 days from the da...
100049,['The CRM/Outlook synchronization process can ...,"[{'is_selected': 0, 'passage_text': 'Dynamics ...",dynamics crm outlook synchronization process,177008,DESCRIPTION,[]
10005,"[""The symptoms of an intolerance to barley are...","[{'is_selected': 0, 'passage_text': 'Just like...",symptoms of an intolerance to barley,1090275,ENTITY,[]
100050,['Wisdom teeth recovery time is three to four ...,"[{'is_selected': 1, 'passage_text': 'You shoul...",how long to recover from wisdom teeth removal,271872,NUMERIC,[]
100051,"['From $26,000 to $39,000 a year']","[{'is_selected': 0, 'passage_text': 'If you ar...",average pharmacy tech salary,40287,NUMERIC,[The average salary for a pharmacy technician ...
100052,['1 Skin care: For a clearer complexion and to...,"[{'is_selected': 1, 'passage_text': 'Major Ben...",benefits of lymphatic drainage facial,50983,DESCRIPTION,[]
10006,['The symptoms of Urinary tract infection is b...,"[{'is_selected': 0, 'passage_text': 'Women may...",symptoms of an uti sensation,1090274,ENTITY,[]
100061,"[""Half of the country's Spanish-speakers resid...","[{'is_selected': 0, 'passage_text': 'Spanish l...",english is the official state language in some...,180613,ENTITY,[]
...,...,...,...,...,...,...
99936,['$48.00'],"[{'is_selected': 1, 'passage_text': '1 A heart...",how much does it cost for dog to be tested for...,314458,NUMERIC,[The cost for dog to be tested for heartworms ...
99939,"['$52,000']","[{'is_selected': 1, 'passage_text': 'The avera...",average salary for college grad,42212,NUMERIC,[The average salary for a college graduate is ...
9994,['The symptoms of Ancylostomiasis include rash...,"[{'is_selected': 0, 'passage_text': 'Symptoms ...",symptoms ancylostomiasis,1090288,ENTITY,[]
99941,['Moisture should penetrate to about 6 to 8 in...,"[{'is_selected': 0, 'passage_text': 'Knowing h...",how to properly water your grass,373938,DESCRIPTION,[]
99944,['A membrane-bound compartment or structure in...,"[{'is_selected': 0, 'passage_text': 'However, ...",cell organelles definition,89573,DESCRIPTION,[Cell organelles is a membrane bound compartme...
99946,"['Yes, bactrim work to treat diverticulitis.']","[{'is_selected': 0, 'passage_text': 'If the pa...",does bactrim work to treat diverticulitis,163622,DESCRIPTION,[]
99948,"['Yes,Rosacea is a facial skin condition that ...","[{'is_selected': 0, 'passage_text': 'By Mayo C...",does adult acne rosacea give you blepharitis,162662,DESCRIPTION,[]
99949,['Yes'],"[{'is_selected': 0, 'passage_text': 'It turns ...",do gemstones have thermal properties,156436,DESCRIPTION,[]
9995,"['Symptoms of hemothorax include: chest pain, ...","[{'is_selected': 1, 'passage_text': 'Symptoms ...",symptoms and signs of massive hemothorax,1090287,ENTITY,[]
99953,['One-thousanth'],"[{'is_selected': 0, 'passage_text': '1 To conv...",how many milliliters are in a meter?,289301,NUMERIC,[There are one thousand milliliters in a meter.]
99954,"['Mastication, taste, deglutition, articulatio...","[{'is_selected': 0, 'passage_text': 'Tongue an...",function of tongue,192540,DESCRIPTION,"[The function of the tongue is mastication, ta..."
99960,['Generally 10 months'],"[{'is_selected': 0, 'passage_text': 'Homepage ...",how many months in a university academic year,289922,NUMERIC,[There are generally 10 months in a university...
99963,['One millimeter of length converted to micron...,"[{'is_selected': 0, 'passage_text': 'Convertin...",convert microns to millimeters,98729,NUMERIC,[One millimeter of length converted to micron ...
99967,['It refers to electronic harassment or bullyi...,"[{'is_selected': 1, 'passage_text': 'Cyberbull...",cyber harassment definition,114698,DESCRIPTION,[]
99969,['Ginger has long been used in Asia to treat m...,"[{'is_selected': 0, 'passage_text': 'Cesar’s A...",how to keep a dog from getting motion sickness,366060,DESCRIPTION,[]
9997,['Symptoms of perimenopause may include: irreg...,"[{'is_selected': 0, 'passage_text': 'Perimenop...",symptoms for premenopausal,1090285,ENTITY,[]
99975,['About 12 minutes.'],"[{'is_selected': 0, 'passage_text': '{{model.a...",how long do you cook a hard boiled egg,247441,NUMERIC,[]
99977,['It is recommended that you take a practice n...,"[{'is_selected': 1, 'passage_text': 'Oklahoma ...",how to become a notary oklahoma,345237,DESCRIPTION,[It is recommended that you take a practice no...
9998,['The symptoms of gallbladder attack include r...,"[{'is_selected': 0, 'passage_text': 'CT scan m...",symptoms gallbladder attack,1090284,ENTITY,[]
99982,['25-26 minutes.'],"[{'is_selected': 0, 'passage_text': '1 Top wit...",how long do you bake muffins,247194,NUMERIC,[]
99985,['$2 to $5 per square foot.'],"[{'is_selected': 0, 'passage_text': 'Vinyl, ac...",cost per foot on hardy plank installation,108172,NUMERIC,[]
99986,['$ 50 to $ 200'],"[{'is_selected': 1, 'passage_text': 'according...",how much does a pap smear cost,310713,NUMERIC,[]
99987,['1 to 2 days.'],"[{'is_selected': 0, 'passage_text': 'When I wa...",how long does it take to mail a card usps,257688,NUMERIC,[]
99988,['The meaning of glioma is a tumor springing f...,"[{'is_selected': 0, 'passage_text': 'Optic Gli...",glioma meaning,195199,DESCRIPTION,[]
9999,['The symptoms of a bad rear main seal are sli...,"[{'is_selected': 0, 'passage_text': 'If you di...",symptoms of a bad main seal,1090283,ENTITY,[]
99990,"['Pizza, pasta and ice cream.']","[{'is_selected': 0, 'passage_text': 'Kashmiri ...",different types of cuisines,150337,DESCRIPTION,[]
99992,"['Yes, electric cleansers are safe.']","[{'is_selected': 0, 'passage_text': 'Features ...",are electric cleansers safe?,22241,DESCRIPTION,[]
99995,"['It is defined as the quality of being wide, ...","[{'is_selected': 0, 'passage_text': '1 The sta...",define width,129177,NUMERIC,[]
99996,['Human Resource Management is the term used t...,"[{'is_selected': 1, 'passage_text': 'Human Res...",forbes definition of human resource management,190655,DESCRIPTION,[]
99999,['List the elements you want to include in a h...,"[{'is_selected': 0, 'passage_text': 'Business ...",how to offer health insurance to employees,371455,DESCRIPTION,[]

In [34]:
y

0         False
1         False
10        False
100       False
1000      False
10000     False
100000    False
100001    False
100002    False
100003    False
100004    False
100005    False
100006    False
100007    False
100008    False
100009    False
10001     False
100010    False
100011    False
100012    False
100013    False
100014    False
100015    False
100016    False
100017    False
100018    False
100019    False
10002     False
100020    False
100021    False
          ...
99972     False
99973     False
99974     False
99975     False
99976     False
99977     False
99978     False
99979     False
9998      False
99980     False
99981     False
99982     False
99983     False
99984     False
99985     False
99986     False
99987     False
99988     False
99989     False
9999      False
99990     False
99991     False
99992     False
99993     False
99994     False
99995     False
99996     False
99997     False
99998     False
99999     False
Name: answers, Length: 101093, dtype: bool

In [15]:
df_selected = df_train[~x]

In [16]:
df_selected

,answers,passages,query,query_id,query_type,wellFormedAnswers
0,['The immediate impact of the success of the m...,"[{'is_selected': 1, 'passage_text': 'The prese...",)what was the immediate impact of the success ...,1185869,DESCRIPTION,[]
1,['Restorative justice that fosters dialogue be...,"[{'is_selected': 0, 'passage_text': 'group dis...",_________ justice is designed to repair the ha...,1185868,DESCRIPTION,[]
10,['The reasons why Stalin wanted to control Eas...,"[{'is_selected': 0, 'passage_text': 'Western b...",why did stalin want control of eastern europe,1185854,DESCRIPTION,[]
100,['Nails rust in water because water allows the...,"[{'is_selected': 0, 'passage_text': 'what to D...",why do nails get rusty,1185755,DESCRIPTION,[]
1000,"['Depona Ab is a library in Vilhelmina, Sweden.']","[{'is_selected': 0, 'passage_text': 'A preview...",depona ab,1184773,DESCRIPTION,[]
100000,"['$43,746 for the 2014-2015 academic year.']","[{'is_selected': 0, 'passage_text': 'the cost ...",nyu tuition cost,467556,NUMERIC,[]
100001,['Before the age of 2–4 years.'],"[{'is_selected': 0, 'passage_text': 'In an eff...",at what age do kids start to hold memories,28213,NUMERIC,[]
100002,['Americans brush for just under the two minut...,"[{'is_selected': 0, 'passage_text': 'Your dent...",average teeth brushing time,44588,NUMERIC,[]
100003,"['Yes, funner is a word.']","[{'is_selected': 0, 'passage_text': 'Taken fro...",is funner a word?,410717,DESCRIPTION,[]
100005,"['An abbreviation of Conformite Conformité, eu...","[{'is_selected': 0, 'passage_text': 'CE Certif...",what is ce certified,728808,DESCRIPTION,[]
10001,['The customer support phone number of BancFir...,"[{'is_selected': 0, 'passage_text': 'Oklahoma ...",bancfirst customer service number,1174761,NUMERIC,[]
100011,"['DeWitt is located in Clinton County, Michiga...","[{'is_selected': 0, 'passage_text': 'DeWitt wa...",what county is dewitt michigan in?,605123,LOCATION,[]
100013,"[""A motorized oxygen mask doesn't qualify to m...","[{'is_selected': 1, 'passage_text': 'It might ...",using cpap without prescription,534802,DESCRIPTION,[]
100014,"[""It allows passengers to check-in to a flight...","[{'is_selected': 0, 'passage_text': 'A confirm...",what is early bird check in southwest,742216,ENTITY,[]
100016,['Bartholomew'],"[{'is_selected': 0, 'passage_text': 'WELCOME T...",what county is columbus city in,604568,LOCATION,[Columbus is a city in Bartholomew County.]
100017,['Social security administration in Bellevue W...,"[{'is_selected': 0, 'passage_text': 'Local soc...",social security administration in bellevue wa ...,499805,NUMERIC,[]
100018,['Yes whiskers are used to help balance as wel...,"[{'is_selected': 0, 'passage_text': 'Yes, whis...",are whiskers on cats used for balance,26191,DESCRIPTION,[]
100019,"['Shelton is in Fairfield County, Connecticut,...","[{'is_selected': 0, 'passage_text': 'My husban...","what county is shelton, ct",612660,LOCATION,[]
10002,"['Yes, the bachelor is legal.']","[{'is_selected': 0, 'passage_text': 'Arconic’s...",is the bachelor legal,1174759,DESCRIPTION,[]
100020,"['Average $111,082,']","[{'is_selected': 1, 'passage_text': 'Bp Americ...",what is BP level j salary,672511,NUMERIC,[]
100022,"[""DBA means 'Doing business as' is a term that...","[{'is_selected': 0, 'passage_text': 'In this p...",what dba mean,617187,DESCRIPTION,[]
100023,"['$4,625 per month.']","[{'is_selected': 1, 'passage_text': 'According...",average cost of assisted living in washington ...,33073,NUMERIC,[]
100025,['Chronic Obstructive Pulmonary Disease and So...,"[{'is_selected': 0, 'passage_text': 'Disabilit...",what disability is copd,620911,DESCRIPTION,[]
100027,['A contemporary Asian dish consisting of an o...,"[{'is_selected': 0, 'passage_text': 'In one co...",what is a omurice omelet,693333,DESCRIPTION,[An omurice omelet is a contemporary Asian dis...
100030,['A Jeep Compass Alternator Replacement is bet...,"[{'is_selected': 1, 'passage_text': 'The avera...",how much does it cost to change a jeep alternator,315061,NUMERIC,[The cost for a Jeep Compass Alternator Replac...
100031,['Crucial for proper brain function and plays ...,"[{'is_selected': 0, 'passage_text': 'Folate an...",what does folic acid do,637779,DESCRIPTION,[Folic acid is crucial for proper brain functi...
100033,['Pinellas County'],"[{'is_selected': 0, 'passage_text': '1 To chan...",what county is seminole fl in,612569,LOCATION,"[Seminole, Florida is in Pinellas County.]"
100034,['$4250'],"[{'is_selected': 0, 'passage_text': '1 A singl...",average cost dental implant,32055,NUMERIC,[The Average cost for Dental Implant is $4250.]
100035,['Yes'],"[{'is_selected': 1, 'passage_text': 'Big Bus T...",tripadvisor does the london hop on off bus pri...,524802,NUMERIC,[]
100036,['A ring of small red or skin-coloured bumps'],"[{'is_selected': 0, 'passage_text': 'Granuloma...",what does granuloma annulare look like,638438,DESCRIPTION,[]
...,...,...,...,...,...,...
9995,['The Eastern part of Texas is in the Central ...,"[{'is_selected': 0, 'passage_text': 'Central T...",is texas central time or eastern time,1174767,DESCRIPTION,[]
99951,"['Turkey, Lebanon, Syria, Jordan, and Israel.']","[{'is_selected': 1, 'passage_text': 'The count...",list of countries in eastern mediterranean region,440697,LOCATION,[]
99952,['A county island is an area of unincorporated...,"[{'is_selected': 1, 'passage_text': 'A county ...",what is an unincorporated island in a city,717553,LOCATION,[A county island is an area of unincorporated ...
99954,['Applied to a machine every time the operatin...,"[{'is_selected': 0, 'passage_text': 'Group Pol...",what group policies are applied,664606,DESCRIPTION,[Group policies are applied to a machine every...
99956,"['$61,230 per year. ']","[{'is_selected': 0, 'passage_text': 'An Execut...",how much does executive driector of family make,313785,NUMERIC,"[An executive director of a family makes $61,2..."
99959,['An explicit formula is a formula we can use ...,"[{'is_selected': 0, 'passage_text': 'explicit ...",what does explicit formula mean,637272,DESCRIPTION,[]
99960,"['No, it is a city.']","[{'is_selected': 0, 'passage_text': 'Memphis S...",is memphis a state,417820,DESCRIPTION,[]
99963,['Completely Automated Public Turing Test to T...,"[{'is_selected': 0, 'passage_text': 'Freebase(...",what does the acronym captcha stand for,649330,DESCRIPTION,[The acronym CAPTCHA stands for Completely Aut...
99965,"['No, it is GMT/UTC - 6h during Standard Time ...","[{'is_selected': 0, 'passage_text': 'Central S...",is chicago cst time,406079,DESCRIPTION,[]
99966,"['Rodents, fish, crustaceans, amphibians, and ...","[{'is_selected': 0, 'passage_text': 'Mink trac...",what do mink eat,623976,ENTITY,"[Mink eats rodents, fish, crustaceans, amphibi..."
99967,['Schizophrenia or suicidal behavior.'],"[{'is_selected': 1, 'passage_text': 'Clozapine...",clozapine interacts with what pain medication,93621,ENTITY,[]
99968,['Feel worthless and hopeless'],"[{'is_selected': 0, 'passage_text': 'Do one bi...",what happens when someone heart is broken,667354,DESCRIPTION,[]
9997,"['Yes, Charles Bronson is dead.']","[{'is_selected': 0, 'passage_text': 'After mov...",is the actor charles bronson dead,1174765,PERSON,[]
99972,['Yes'],"[{'is_selected': 0, 'passage_text': 'He was th...",was william henry harrison a republican,541259,DESCRIPTION,[]
99973,"['Fairbury is in Livingston County, Illinois.']","[{'is_selected': 1, 'passage_text': '407 Walnu...",what county is fairbury il,605770,LOCATION,[]
99977,"['11 pounds', '22-50 pounds']","[{'is_selected': 0, 'passage_text': 'Rated 4 o...",weight evenflo maestro,547249,NUMERIC,[The weight of Evenflo Maestro is 11 pounds.]
9998,"['Yes, iPad Pro is water resistant.']","[{'is_selected': 0, 'passage_text': 'Apple's n...",is the apple ipad water resistant?,1174764,DESCRIPTION,[]
99981,['908 kWh'],"[{'is_selected': 1, 'passage_text': 'The avera...",average kwh per household in us,38107,NUMERIC,[]
99985,"['Yes, Luxury vinyl flooring is a diy job.']","[{'is_selected': 1, 'passage_text': 'Luxury vi...",is vinyl flooring a diy job,430897,DESCRIPTION,[]
99986,['A floating museum is in New York City.'],"[{'is_selected': 1, 'passage_text': 'Intrepid ...",what city is a floating museum,595815,LOCATION,[]
99988,"['Carbon dioxide, methane and other greenhouse...","[{'is_selected': 1, 'passage_text': 'Global wa...",what causes the greenhouse effect,592625,DESCRIPTION,[]
9999,"['Yes, the asthenosphere made of iron and nick...","[{'is_selected': 1, 'passage_text': 'The asthe...",is the asthenosphere made of iron and nickel,1174763,DESCRIPTION,[]
99991,['Amuse means keeping yourself or someone else...,"[{'is_selected': 0, 'passage_text': 'Much late...",the definition of amuse,515137,DESCRIPTION,[]
99992,"['WBC is 5 to 10 K/uL, HGB is 12 to 17.4 g/dL.']","[{'is_selected': 0, 'passage_text': 'A complet...",what is human blood value on a cbc,756122,DESCRIPTION,[]
99993,['Used to treat inflammation of small areas of...,"[{'is_selected': 0, 'passage_text': 'What is c...",what is a cortisone injection used for,679433,DESCRIPTION,[A cortisone injection is used to treat inflam...
99994,['(575) 527-1709'],"[{'is_selected': 0, 'passage_text': '1 The Con...",fort selden roofing las cruces phone number,191150,NUMERIC,[]
99995,['255077833'],"[{'is_selected': 0, 'passage_text': 'Complete ...",nasa credit union routing number,462353,NUMERIC,[255077833 is NASA's credit union routing numb...
99996,['Galveston County'],"[{'is_selected': 0, 'passage_text': 'Most of t...",what county is hitchcock texas located in,607295,LOCATION,[]
99997,['All about great blowout style for about thir...,"[{'is_selected': 0, 'passage_text': 'And with ...",what is blowout for hair,724819,DESCRIPTION,[]
99999,"['Walrus, star fish, eel, crabs, jelly fish, a...","[{'is_selected': 1, 'passage_text': 'ANIMALS. ...",name some organisms that might live in a marin...,461916,ENTITY,"[Walrus, star fish, eel, crabs, jelly fish, an..."

In [51]:
503370 + 55636 - 524188.0

34818.0

In [11]:
df_train.dtypes

answers              object
passages             object
query                object
query_id              int64
query_type           object
wellFormedAnswers    object
dtype: object

In [10]:
df_train.loc[99998]

answers                                           [No Answer Present.]
passages             [{'is_selected': 0, 'passage_text': 'Isaac Bel...
query                    what car does isaac bell drive in the wrecker
query_id                                                        583161
query_type                                                      ENTITY
wellFormedAnswers                                                   []
Name: 99998, dtype: object

In [2]:
columns = ['query_id','1','2','3','4','5','6','7','8','9','10']
ans_headers = ['1','2','3','4','5','6','7','8','9','10']

In [3]:
one = pd.read_csv('./answer2_290_Epoch2_160.tsv',names=columns,delimiter='\t')
two = pd.read_csv('./answer2_290_mixed_Epoch3.tsv',names=columns,delimiter='\t')

In [4]:
import numpy as np

In [20]:
def softmax(row):
    row = row.tolist()
#     print (row)
    logits = row[1:]
    exps = [np.exp(i) for i in logits]
    sum_of_exps = sum(exps)
    softmax_ = [j/sum_of_exps for j in exps]
#     print (softmax_)
    return pd.Series(softmax_,index=ans_headers)

In [6]:
df_one = one.copy()
df_two = two.copy()

In [11]:
one.loc[1]

query_id    1.136956e+06
1          -3.037337e+00
2          -1.468039e+00
3          -1.505129e+00
4          -1.187077e+00
5           1.237919e-01
6           2.826501e+00
7           2.452425e+00
8          -2.953604e+00
9           1.316775e+00
10          3.026641e+00
Name: 1, dtype: float64

In [21]:
softmax(one.loc[1])

1     0.000874
2     0.004200
3     0.004047
4     0.005563
5     0.020634
6     0.307855
7     0.211781
8     0.000951
9     0.068027
10    0.376068
dtype: float64

In [22]:
one[:3].apply(lambda x: softmax(x), axis=1)

,1,2,3,4,5,6,7,8,9,10
0,0.000255,0.207960,0.109331,0.000646,0.000461,0.135720,0.226582,0.032119,0.025350,0.261575
1,0.000874,0.004200,0.004047,0.005563,0.020634,0.307855,0.211781,0.000951,0.068027,0.376068
2,0.046619,0.000622,0.133406,0.012808,0.139019,0.002631,0.152140,0.071120,0.429115,0.012521

In [29]:
df_one

,query_id,1,2,3,4,5,6,7,8,9,10
0,1136966,0.000255,0.207960,0.109331,0.000646,0.000461,0.135720,0.226582,0.032119,0.025350,0.261575
1,1136956,0.000874,0.004200,0.004047,0.005563,0.020634,0.307855,0.211781,0.000951,0.068027,0.376068
2,1136841,0.046619,0.000622,0.133406,0.012808,0.139019,0.002631,0.152140,0.071120,0.429115,0.012521
3,1125025,0.000062,0.022328,0.000501,0.330520,0.000136,0.003739,0.000057,0.003742,0.033499,0.605415
4,86062,0.016662,0.006375,0.141055,0.278353,0.070753,0.003164,0.372122,0.023709,0.081648,0.006159
5,80665,0.005803,0.000301,0.141577,0.124222,0.050627,0.001644,0.335871,0.173974,0.008389,0.157593
6,180241,0.298560,0.002401,0.000434,0.000400,0.000424,0.078082,0.311431,0.000423,0.307268,0.000578
7,234133,0.000457,0.753236,0.000323,0.000190,0.000328,0.195292,0.001935,0.000178,0.013999,0.034060
8,76402,0.105442,0.192783,0.021330,0.054314,0.115750,0.018151,0.130860,0.098685,0.196183,0.066501
9,335954,0.002493,0.855348,0.005912,0.002706,0.010216,0.105480,0.002800,0.002311,0.002987,0.009748
10,308586,0.000100,0.001951,0.024073,0.048153,0.443328,0.092432,0.170259,0.079687,0.013661,0.126355
11,1125023,0.099154,0.003017,0.013762,0.000441,0.000625,0.586802,0.175009,0.000849,0.062949,0.057394
12,24854,0.000471,0.906715,0.019712,0.002121,0.001225,0.039564,0.008505,0.006834,0.012740,0.002114
13,168342,0.017324,0.248971,0.015005,0.001457,0.203284,0.087025,0.117167,0.183928,0.065891,0.059947
14,172329,0.063284,0.075672,0.004831,0.156025,0.173136,0.103200,0.366741,0.012150,0.007309,0.037653
15,129511,0.008698,0.000049,0.002640,0.296163,0.366685,0.027343,0.296163,0.001100,0.001100,0.000058
16,243561,0.102306,0.000305,0.193703,0.115389,0.000854,0.086251,0.311442,0.006184,0.076246,0.107319
17,17676,0.445622,0.000078,0.000468,0.032220,0.005641,0.000271,0.003837,0.485520,0.024759,0.001584
18,1233,0.027621,0.011138,0.000321,0.005999,0.020605,0.518933,0.000334,0.395232,0.018021,0.001796
19,220038,0.123422,0.000361,0.000284,0.103442,0.447363,0.005325,0.076375,0.000525,0.242640,0.000263
20,1125021,0.001110,0.016707,0.069234,0.007770,0.002095,0.003555,0.028319,0.476527,0.374211,0.020472
21,133488,0.000490,0.000459,0.000177,0.000225,0.000230,0.286896,0.476808,0.233359,0.000626,0.000730
22,285070,0.284843,0.000027,0.000172,0.031454,0.001067,0.027872,0.026690,0.298575,0.228447,0.100854
23,366024,0.122209,0.122516,0.130668,0.165654,0.026364,0.129696,0.044571,0.039394,0.146750,0.072177
24,74733,0.066797,0.000177,0.137355,0.128366,0.002571,0.126919,0.090965,0.187395,0.048591,0.210864
25,75624,0.028633,0.461138,0.169843,0.020008,0.160470,0.003738,0.124505,0.004827,0.019482,0.007356
26,1125020,0.103704,0.006707,0.004083,0.001875,0.354918,0.007753,0.037461,0.400961,0.056669,0.025869
27,94956,0.001178,0.007327,0.008420,0.012876,0.001685,0.000067,0.000071,0.001131,0.958506,0.008740
28,249931,0.000086,0.000083,0.001225,0.031095,0.944550,0.015681,0.006792,0.000292,0.000091,0.000105
29,313747,0.101998,0.017251,0.000099,0.018821,0.017108,0.065045,0.000046,0.002700,0.012083,0.764849
...,...,...,...,...,...,...,...,...,...,...,...
41508,230330,0.179698,0.000171,0.019927,0.391713,0.038041,0.014306,0.131149,0.219966,0.004855,0.000174
41509,124889,0.000424,0.000784,0.002056,0.000976,0.425558,0.000369,0.563027,0.000299,0.000136,0.006371
41510,91079,0.000351,0.088806,0.609695,0.000454,0.136293,0.000897,0.052041,0.060670,0.000942,0.049850
41511,115325,0.232819,0.029049,0.268348,0.000035,0.000070,0.000038,0.250043,0.219549,0.000025,0.000024
41512,178523,0.008431,0.007268,0.086505,0.000889,0.000402,0.033428,0.010614,0.779669,0.016070,0.056724
41513,219898,0.390039,0.303053,0.036408,0.029138,0.000102,0.006846,0.013942,0.000384,0.001730,0.218358
41514,154975,0.007380,0.010934,0.157756,0.056830,0.559520,0.045547,0.004013,0.023895,0.037290,0.096836
41515,1125032,0.000156,0.071620,0.000292,0.005277,0.000049,0.000136,0.364432,0.017771,0.003025,0.537243
41516,237994,0.504536,0.074522,0.015327,0.027105,0.048730,0.038237,0.155427,0.004252,0.000901,0.130963
41517,205584,0.000527,0.012014,0.060964,0.010627,0.074915,0.000474,0.001382,0.836552,0.000437,0.002107
41518,373896,0.046570,0.002237,0.014093,0.187618,0.181850,0.107595,0.159494,0.072013,0.108168,0.120363
41519,65396,0.277996,0.000697,0.195249,0.184840,0.000102,0.000401,0.163995,0.176337,0.000114,0.000269
41520,49023,0.015302,0.000993,0.000332,0.000864,0.016788,0.001300,0.048552,0.001650,0.000310,0.913908
41521,249247,0.176299,0.521705,0.021953,0.000150,0.017041,0.000179,0.187074,0.075307,0.000166,0.000126
41522,170385,0.052245,0.004771,0.021052,0.005434,0.432145,0.195304,0.022688,0.006895,0.218552,0.040913
41523,84257,0.001038,0.036827,0.010043,0.121648,0.196312,0.051845,0.222233,0.066932,0.292757,0.000365
41524,149323,0.272468,0.002985,0.261358,0.350741,0.020156,0.049283,0.009032,0.005891,0.024116,0.003970
41525,227958,0.083631,0.001335,0.294117,0.001106,0.028539,0.001426,0.001224,0.041799,0.379672,0.167150
41526,68916,0.343311,0.001902,0.152298,0.000447,0.076385,0.071162,0.006841,0.166125,0.177910,0.003621
41527,60667,0.000638,0.000874,0.285884,0.288606,0.000137,0.000019,0.018730,0.288606,0.116148,0.000359
41528,1125028,0.004438,0.326042,0.004441,0.015926,0.206054,0.283391,0.011369,0.006569,0.141009,0.000761
41529,115071,0.004945,0.002917,0.004997,0.187097,0.002726,0.005939,0.004505,0.006751,0.729136,0.050987
41530,341221,0.992338,0.000168,0.006580,0.000185,0.000162,0.000060,0.000088,0.000201,0.000078,0.000140
41531,287953,0.386280,0.262636,0.044612,0.257017,0.000879,0.000740,0.000873,0.044089,0.001058,0.001815
41532,24494,0.394976,0.100190,0.079163,0.005601,0.220410,0.003104,0.190203,0.002363,0.002579,0.001411
41533,1125027,0.411261,0.013006,0.065613,0.000720,0.000841,0.236408,0.014095,0.000741,0.006030,0.251286
41534,354157,0.198523,0.738551,0.015615,0.001064,0.004144,0.000237,0.000514,0.008820,0.006934,0.025599
41535,332649,0.000412,0.212548,0.000950,0.003891,0.000742,0.001826,0.001062,0.215318,0.000412,0.562840
41536,374435,0.196550,0.010566,0.187352,0.086258,0.031229,0.135395,0.070381,0.083037,0.116540,0.082691
41537,123628,0.001631,0.170765,0.204136,0.000035,0.085727,0.001056,0.256251,0.278046,0.002010,0.000343

In [23]:
df_one[ans_headers] = one.apply(lambda x: softmax(x), axis=1)

In [27]:
df_two[ans_headers] = two.apply(lambda x: softmax(x), axis=1)

In [6]:
two.head()

,query_id,1,2,3,4,5,6,7,8,9,10
0,1136966,-3.471546,3.119705,2.748143,-2.061335,-2.470538,3.298495,3.491955,1.573026,1.000348,3.620442
1,1136956,-3.726930,-2.489444,-2.292486,-1.507174,-0.444416,2.315248,1.919158,-3.663156,0.951928,2.571643
2,1136841,0.069452,-4.416095,1.386632,-0.630060,1.512524,-3.993858,1.339767,0.383412,2.454320,-0.877230
3,1125025,-4.738125,0.573662,-2.688248,3.691872,-3.160819,-1.016214,-5.073241,-0.230091,1.103286,4.322522
4,86062,0.369257,-0.616475,2.434665,3.228459,1.249426,-1.635600,3.795533,0.576618,1.744282,-0.599759

In [28]:
df_two.head()

,query_id,1,2,3,4,5,6,7,8,9,10
0,1136966,0.000217,0.157974,0.108948,0.000888,0.000590,0.188901,0.229220,0.033641,0.018974,0.260647
1,1136956,0.000714,0.002460,0.002996,0.006570,0.019017,0.300365,0.202129,0.000761,0.076836,0.388151
2,1136841,0.038959,0.000439,0.145427,0.019356,0.164938,0.000670,0.138769,0.053328,0.422997,0.015117
3,1125025,0.000072,0.014599,0.000559,0.330017,0.000349,0.002977,0.000052,0.006535,0.024793,0.620047
4,86062,0.015248,0.005690,0.120284,0.266042,0.036768,0.002054,0.469058,0.018762,0.060309,0.005786

In [32]:
df_one.head()

,query_id,1,2,3,4,5,6,7,8,9,10
0,1136966,0.000255,0.207960,0.109331,0.000646,0.000461,0.135720,0.226582,0.032119,0.025350,0.261575
1,1136956,0.000874,0.004200,0.004047,0.005563,0.020634,0.307855,0.211781,0.000951,0.068027,0.376068
2,1136841,0.046619,0.000622,0.133406,0.012808,0.139019,0.002631,0.152140,0.071120,0.429115,0.012521
3,1125025,0.000062,0.022328,0.000501,0.330520,0.000136,0.003739,0.000057,0.003742,0.033499,0.605415
4,86062,0.016662,0.006375,0.141055,0.278353,0.070753,0.003164,0.372122,0.023709,0.081648,0.006159

In [33]:
df_add = (df_one + df_two)/2

In [34]:
df_add

,query_id,1,2,3,4,5,6,7,8,9,10
0,1136966,0.000236,0.182967,0.109140,0.000767,0.000526,0.162310,0.227901,0.032880,0.022162,0.261111
1,1136956,0.000794,0.003330,0.003522,0.006066,0.019825,0.304110,0.206955,0.000856,0.072432,0.382109
2,1136841,0.042789,0.000530,0.139417,0.016082,0.151978,0.001650,0.145455,0.062224,0.426056,0.013819
3,1125025,0.000067,0.018463,0.000530,0.330269,0.000243,0.003358,0.000054,0.005139,0.029146,0.612731
4,86062,0.015955,0.006033,0.130670,0.272197,0.053760,0.002609,0.420590,0.021235,0.070978,0.005973
5,80665,0.004396,0.000319,0.126358,0.098858,0.050987,0.001382,0.388285,0.142608,0.006805,0.180002
6,180241,0.324483,0.001672,0.000431,0.000404,0.000414,0.090528,0.302821,0.000432,0.278218,0.000597
7,234133,0.000378,0.755315,0.000291,0.000178,0.000271,0.197634,0.001565,0.000167,0.013195,0.031007
8,76402,0.105587,0.168524,0.024254,0.073354,0.140088,0.023641,0.127861,0.095817,0.179389,0.061484
9,335954,0.002834,0.896847,0.004928,0.003045,0.008997,0.064591,0.003079,0.002570,0.003118,0.009990
10,308586,0.000163,0.001700,0.027819,0.053641,0.406211,0.111699,0.170368,0.066112,0.014156,0.148130
11,1125023,0.104115,0.004029,0.015476,0.000530,0.000677,0.565420,0.182221,0.000667,0.068044,0.058820
12,24854,0.000554,0.904812,0.017565,0.002373,0.001405,0.046044,0.006245,0.007035,0.012351,0.001618
13,168342,0.012303,0.302860,0.011341,0.001253,0.226806,0.078378,0.105033,0.162731,0.054903,0.044392
14,172329,0.050862,0.062471,0.003625,0.169319,0.200281,0.117675,0.348691,0.009638,0.006761,0.030677
15,129511,0.006693,0.000043,0.002158,0.275120,0.415919,0.023456,0.275120,0.000722,0.000722,0.000047
16,243561,0.108661,0.000249,0.190771,0.113176,0.001147,0.091422,0.296884,0.008532,0.086332,0.102825
17,17676,0.503431,0.000062,0.000785,0.027525,0.005151,0.000181,0.003343,0.439215,0.018894,0.001412
18,1233,0.033013,0.010541,0.000403,0.005210,0.018415,0.519758,0.000401,0.388749,0.021651,0.001858
19,220038,0.134054,0.000330,0.000270,0.139112,0.427662,0.003550,0.086548,0.000443,0.207775,0.000256
20,1125021,0.001520,0.015542,0.074424,0.011492,0.002012,0.004005,0.021890,0.432129,0.412489,0.024496
21,133488,0.000309,0.000285,0.000151,0.000228,0.000206,0.253883,0.497448,0.246307,0.000694,0.000488
22,285070,0.241278,0.000034,0.000195,0.022746,0.001302,0.032826,0.030752,0.350413,0.230364,0.090090
23,366024,0.115581,0.113571,0.127768,0.173292,0.022163,0.132404,0.045157,0.043451,0.147599,0.079013
24,74733,0.070355,0.000235,0.122648,0.117149,0.003143,0.131131,0.084297,0.158644,0.043504,0.268893
25,75624,0.027831,0.406096,0.198231,0.021715,0.172403,0.003689,0.134131,0.005528,0.023810,0.006566
26,1125020,0.115464,0.007573,0.003403,0.002864,0.400671,0.007595,0.049033,0.339187,0.052034,0.022176
27,94956,0.001194,0.006577,0.007450,0.012385,0.001463,0.000078,0.000081,0.000948,0.961880,0.007943
28,249931,0.000066,0.000065,0.000798,0.024904,0.954344,0.012847,0.006564,0.000258,0.000075,0.000079
29,313747,0.101423,0.018193,0.000069,0.019715,0.019219,0.066538,0.000041,0.002691,0.010306,0.761805
...,...,...,...,...,...,...,...,...,...,...,...
41508,230330,0.185035,0.000161,0.017323,0.431289,0.034958,0.012976,0.115605,0.197558,0.004934,0.000162
41509,124889,0.000578,0.000872,0.001796,0.000842,0.331408,0.000456,0.656829,0.000278,0.000138,0.006804
41510,91079,0.000298,0.080099,0.610642,0.000411,0.149153,0.000775,0.050016,0.066236,0.000789,0.041580
41511,115325,0.240536,0.023145,0.274399,0.000035,0.000047,0.000037,0.259344,0.202410,0.000025,0.000022
41512,178523,0.013322,0.013555,0.114925,0.001146,0.000786,0.052918,0.012109,0.705121,0.020760,0.065359
41513,219898,0.402566,0.301469,0.032337,0.028007,0.000156,0.007620,0.013171,0.000404,0.003082,0.211189
41514,154975,0.006483,0.007352,0.158917,0.072791,0.542374,0.059953,0.003489,0.024136,0.034030,0.090476
41515,1125032,0.000110,0.063014,0.000225,0.003635,0.000042,0.000114,0.370664,0.012387,0.002405,0.547404
41516,237994,0.520393,0.086107,0.014582,0.023736,0.046712,0.036324,0.159222,0.003457,0.000924,0.108541
41517,205584,0.000508,0.010678,0.063298,0.009838,0.066089,0.000445,0.001163,0.845389,0.000415,0.002177
41518,373896,0.046829,0.001794,0.013649,0.200940,0.170204,0.114028,0.160669,0.085390,0.096962,0.109534
41519,65396,0.300716,0.000669,0.192441,0.174043,0.000106,0.000387,0.138724,0.192386,0.000126,0.000403
41520,49023,0.014791,0.000870,0.000298,0.000814,0.014675,0.001042,0.056900,0.001488,0.000329,0.908793
41521,249247,0.172008,0.551603,0.019784,0.000101,0.014543,0.000126,0.179203,0.062425,0.000109,0.000097
41522,170385,0.055686,0.009279,0.022000,0.008068,0.417888,0.200232,0.022811,0.007631,0.221577,0.034828
41523,84257,0.000918,0.042203,0.013099,0.131020,0.199114,0.056356,0.238207,0.068313,0.250371,0.000398
41524,149323,0.235337,0.003548,0.258410,0.406362,0.017629,0.038948,0.007227,0.004436,0.024892,0.003210
41525,227958,0.081825,0.001434,0.263113,0.001242,0.024646,0.001517,0.001332,0.038142,0.426225,0.160522
41526,68916,0.360221,0.001469,0.123829,0.000292,0.071850,0.066186,0.005981,0.188942,0.178217,0.003014
41527,60667,0.000539,0.000739,0.285266,0.301407,0.000168,0.000017,0.016102,0.301407,0.094035,0.000321
41528,1125028,0.004216,0.295923,0.003758,0.015939,0.197345,0.305887,0.009560,0.007135,0.159625,0.000610
41529,115071,0.004172,0.002746,0.004231,0.204816,0.002593,0.004836,0.003965,0.007436,0.710372,0.054830
41530,341221,0.992326,0.000120,0.006847,0.000130,0.000131,0.000051,0.000067,0.000139,0.000069,0.000121
41531,287953,0.443591,0.224338,0.039009,0.251573,0.000685,0.000663,0.000679,0.036261,0.000816,0.002384
41532,24494,0.431406,0.102269,0.078801,0.007559,0.191553,0.003570,0.178747,0.002284,0.002376,0.001435
41533,1125027,0.396348,0.014695,0.077536,0.000593,0.000672,0.271400,0.014816,0.000589,0.006873,0.216477
41534,354157,0.189618,0.757385,0.013764,0.000814,0.004322,0.000189,0.000419,0.007111,0.006130,0.020248
41535,332649,0.000370,0.216237,0.000673,0.003637,0.000561,0.001267,0.000751,0.198426,0.000372,0.577705
41536,374435,0.160445,0.009312,0.220627,0.078760,0.027016,0.145041,0.061949,0.100658,0.118606,0.077585
41537,123628,0.001434,0.186673,0.162345,0.000028,0.071920,0.000705,0.273816,0.301048,0.001760,0.000272

In [35]:
df_add.to_csv('./answer.tsv',sep='\t',header=False,index=False)

In [36]:
!head -n 5 answer.tsv

1136966	0.00023609203761854345	0.18296693681018122	0.10913952684692294	0.0007672799897848509	0.0005255406033104089	0.1623103457686734	0.22790102684839325	0.03288013268839202	0.022161821327398933	0.26111129707932446
1136956	0.0007940942368694606	0.003330190508610874	0.0035215284643439143	0.006066467817094089	0.019825311394532516	0.3041101945140504	0.20695535538177115	0.0008557812360992721	0.07243167715162581	0.3821093992950026
1136841	0.042788572503287554	0.0005303174443550345	0.13941689385957434	0.01608183193278996	0.15197838901257738	0.001650206756344249	0.14545460490847714	0.062224109467858515	0.4260561241145436	0.013818950000192221
1125025	6.72364526140951e-05	0.018463332696184425	0.0005303312650424501	0.3302686302956188	0.00024255145834011055	0.00335820728469047	5.4213101824247104e-05	0.005138745672484357	0.02914590322943143	0.6127308485437695
86062	0.015954872884424685	0.00603272231822927	0.13066970890781415	0.2721971785229962	0.05376033266390932	0.002608695852293073	0.4205903211185831	0.021235489084589686	0.0709781641946686	0.005972514452492006